### ISSUE TITLE
wlr_buffer reverted due to frequent aborts

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#1061]
I would get a lot of aborts after starting qutebrowser post-merge. Apologies for insufficiently testing that.

```
#0  0x00007f3c7d08286b in raise () at /usr/lib/libc.so.6
#1  0x00007f3c7d06d40e in abort () at /usr/lib/libc.so.6
#2  0x00007f3c7d06d2e0 in _nl_load_domain.cold.0 () at /usr/lib/libc.so.6
#3  0x00007f3c7d07b112 in  () at /usr/lib/libc.so.6
#4  0x00007f3c7f6994b9 in gles2_wl_drm_buffer_get_size (wlr_renderer=0x7f3c7f6994b9 <gles2_wl_drm_buffer_get_size+110>, buffer=0x9, width=0x7ffe99d00a20, height=0x7ffe99cffeb0)
    at ../subprojects/wlroots/render/gles2/renderer.c:237
        renderer = 0x558b14a1c0f0
#5  0x00007f3c7f6994d7 in gles2_get_dmabuf_formats (wlr_renderer=0x558b14a1c0f0, formats=0x9) at ../subprojects/wlroots/render/gles2/renderer.c:241
        renderer = 0x7f3c7f6994d7 <gles2_get_dmabuf_formats+2>
#6  0x0000558b14a1c0f0 in  ()
#7  0x00007ffe99cfff70 in  ()
#8  0x0000558b14410990 in  ()
#9  0x00007ffe99cfff60 in  ()
#10 0x00007f3c7f69829c in wlr_egl_create_image_from_wl_drm (egl=0x7f3c7f69829c <wlr_egl_create_image_from_wl_drm+269>, data=0x7ffe99cfff60, fmt=0x558b14410990, width=0x7ffe99cfff70, height=0x558b14a1c0f0, inverted_y=0x7ffe99cfff10) at ../subprojects/wlroots/render/egl.c:370
        _inverted_y = -1714421632
        attribs = {32766, 346145008, 21899}
#11 0x00007f3c7f69a26a in gles2_get_texture (wlr_texture=0x558b14410990) at ../subprojects/wlroots/render/gles2/texture.c:22
        __PRETTY_FUNCTION__ = "gles2_get_texture"
#12 0x0000558b1316376d in scissor_output (wlr_output=0x558b1454b710, rect=0x7ffe99cffff0) at ../sway/desktop/output.c:205
        renderer = 0x7f3c7f69a363 <gles2_texture_write_pixels+94>
        __PRETTY_FUNCTION__ = "scissor_output"
        box = {x = 8, y = 1065353216, width = -1714421632, height = 32766}
        ow = 794870442
        oh = -1714421872
        transform = 32766
#13 0x0000558b1316389e in render_texture (wlr_output=0x558b1454b710, output_damage=0x7ffe99d00420, texture=0x558b14a1c0f0, box=0x7ffe99d00070, matrix=0x7ffe99d00080, alpha=1)
    at ../sway/desktop/output.c:228
        i = 0
        renderer = 0x558b14410990
        damage = {extents = {x1 = 8, y1 = 50, x2 = 1608, y2 = 1250}, data = 0x0}
        damaged = true
        nrects = 1
        rects = 0x7ffe99cffff0
#14 0x0000558b13163a09 in render_surface_iterator (surface=0x558b14914e10, sx=0, sy=0, _data=0x7ffe99d001d0) at ../sway/desktop/output.c:262
        data = 0x7ffe99d001d0
        wlr_output = 0x558b1454b710
        rotation = 0
        output_damage = 0x7ffe99d00420
        alpha = 1
        box = {x = 8, y = 50, width = 1600, height = 1200}
        intersects = true
        matrix = {0.833333373, 0, -0.995833337, 0, -1.11111104, 0.953703701, 0, 0, 1}
        transform = WL_OUTPUT_TRANSFORM_NORMAL
#15 0x00007f3c7f6bd4df in subsurface_handle_place_above (client=0x558b14914e10, resource=0x0, sibling_resource=0x558b131638d0 <render_surface_iterator>)
    at ../subprojects/wlroots/types/wlr_surface.c:800
        subsurface = 0x3f760b61bf800000
        sibling_surface = 0x7ffe3f800000
        sibling = 0x2f60c2aab26f4700
#16 0x00007f3c7f6bd5b6 in subsurface_handle_place_below (client=0x7f3c7f6bd5b6 <subsurface_handle_place_below+59>, resource=0x7ffe99d00130, sibling_resource=0x2f60c2aab26f4700)
    at ../subprojects/wlroots/types/wlr_surface.c:827
        subsurface = 0x7ffe99d001d0
        sibling_surface = 0x558b131638d0 <render_surface_iterator>
        sibling = 0x558b14914e10
#17 0x0000558b13186d80 in view_for_each_surface (view=0x558b145cc4a0, iterator=0x558b131638d0 <render_surface_iterator>, user_data=0x7ffe99d001d0) at ../sway/tree/view.c:360
#18 0x0000558b131633dd in output_view_for_each_surface (view=0x558b145cc4a0, geo=0x7ffe99d001d0, iterator=0x558b131638d0 <render_surface_iterator>, user_data=0x7ffe99d001d0)
    at ../sway/desktop/output.c:133
        data = 0x7ffe99d001d0
#19 0x0000558b13163f13 in render_view_surfaces (view=0x558b145cc4a0, output=0x558b14546350, damage=0x7ffe99d00420, alpha=1) at ../sway/desktop/output.c:346
        data = {root_geo = {x = 4, y = 25, width = 800, height = 600, rotation = 0}, output = 0x558b14546350, damage = 0x7ffe99d00420, alpha = 1}
#20 0x0000558b13163f83 in render_view (output=0x558b14546350, damage=0x7ffe99d00420, con=0x558b14a88c60, colors=0x558b1442b74c) at ../sway/desktop/output.c:356
        view = 0x558b145cc4a0
        box = {x = 3840, y = 42, width = 3840, height = 8}
        output_scale = 2
        color = {0.156862751, 0.333333343, 0.466666669, 1}
#21 0x0000558b131650f7 in render_container_simple (output=0x558b14546350, damage=0x7ffe99d00420, con=0x558b14557130, parent_focused=false) at ../sway/desktop/output.c:651
        colors = 0x558b1442b74c
        title_texture = 0x558b14a72ca0
        marks_texture = 0x0
        child = 0x558b14a88c60
        i = 0
        seat = 0x558b14497030
        focus = 0x558b14a88c60
#22 0x0000558b13165746 in render_container (output=0x558b14546350, damage=0x7ffe99d00420, con=0x558b14557130, parent_focused=false) at ../sway/desktop/output.c:782
        __PRETTY_FUNCTION__ = "render_container"
#23 0x0000558b13165ec6 in render_output (output=0x558b14546350, when=0x7ffe99d00410, damage=0x7ffe99d00420) at ../sway/desktop/output.c:930
        clear_color = {0.25, 0.25, 0.25, 1}
        rects = 0x7ffe99d00420
        nrects = 1
        seat = 0x558b14497030
        focus = 0x558b14a88c60
        wlr_output = 0x558b1454b710
        renderer = 0x558b14410990
        __PRETTY_FUNCTION__ = "render_output"
        damage_whole_before_swap = false
        damage_debug = 0x0
        workspace = 0x558b14557130
#24 0x0000558b131664b7 in damage_handle_frame (listener=0x558b14546448, data=0x558b145b2c70) at ../sway/desktop/output.c:1072
        output = 0x558b14546350
        now = {tv_sec = 7312, tv_nsec = 629676540}
        needs_swap = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 3840, y2 = 2160}, data = 0x0}
#25 0x00007f3c7f6c2229 in wlr_region_transform (dst=0x90, src=0x7f3c7f6c2173 <wlr_region_transform+1127>, transform=32766, width=-1714420592, height=21899)
    at ../subprojects/wlroots/util/region.c:82
        i = 32766
        nrects = -1714420624
        src_rects = 0x558b145b2cd0
        dst_rects = 0x7f3c7f6c2173 <wlr_region_transform+1127>
#26 0x00007f3c7f6b4515 in wlr_matrix_scale (mat=0x2f60c2aab26f4700, x=4.56430936e-41, y=3.13871485e+38) at ../subprojects/wlroots/types/wlr_matrix.c:55
        scale = {-2.15086649e-23, 4.59149455e-41, 3.12727273e+38, 4.56430936e-41, 1.07393675e-26, 3.06870351e-41, 1.10656293e-26, 3.06870351e-41, 2.24207754e-44}
#27 0x00007f3c7f6c2229 in wlr_region_transform (dst=0x558b1442c730, src=0x7f3c7f6c2173 <wlr_region_transform+1127>, transform=32766, width=-1714420432, height=21899)
    at ../subprojects/wlroots/util/region.c:82
        i = 32766
        nrects = -1714420464
        src_rects = 0x558b1454b828
        dst_rects = 0x7f3c7f6c2173 <wlr_region_transform+1127>
#28 0x00007f3c7f6b79a4 in output_cursor_get_box (cursor=0x558b1454b710, box=0x7ffe99d00600) at ../subprojects/wlroots/types/wlr_output.c:401
#29 0x00007f3c7f687717 in drm_connector_move_cursor (output=0x7f3c7f6b79a4 <output_cursor_get_box+12>, x=32766, y=-1714420368) at ../subprojects/wlroots/backend/drm/drm.c:709
        conn = 0x7f3c7f687717 <drm_connector_move_cursor+232>
        drm = 0x1900000004
        plane = 0x558b1454b710
        box = {x = 630091, y = 7312, width = 438619, height = 9}
        width = 21899
        height = -1714420304
        transform = 32766
        ok = 20
#30 0x00007f3c7ba13485 in drmHandleEvent () at /usr/lib/libdrm.so.2
#31 0x00007f3c7f687788 in drm_connector_move_cursor (output=0x0, x=32766, y=-1714418208) at ../subprojects/wlroots/backend/drm/drm.c:721
        conn = 0x900000001
        drm = 0x4
        plane = 0x0
        box = {x = 2137552495, y = 32572, width = 0, height = 0}
        width = 32572
        height = 0
        transform = WL_OUTPUT_TRANSFORM_NORMAL
        ok = 127
#32 0x00007f3c7d85da42 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#33 0x00007f3c7d85c14c in wl_display_run () at /usr/lib/libwayland-server.so.0
#34 0x0000558b13158860 in server_run (server=0x558b133a16c0 <server>) at ../sway/server.c:126
#35 0x0000558b1315822d in main (argc=2, argv=0x7ffe99d00de8) at ../sway/main.c:427
        verbose = 0
        debug = 1
        validate = 0
        long_options = 
            {{name = 0x558b1318e57c "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x558b1318e581 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x558b1318e588 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x558b1318e591 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x558b1318e597 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x558b1318e59f "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x558b1318e5a7 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x558b1318e138 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
        suid = false
```

**Comment by Ongy** [comment]
> #2  0x00007f3c7d06d2e0 in _nl_load_domain.cold.0 () at /usr/lib/libc.so.6

This is interesting, mem-corruption? How deterministic can you trigger it, viable to get a valgrind log?
