### ISSUE TITLE
DRM crash when hotplug happens while on other VT

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#1176]
- Start compositor on VT1
- Switch to VT2
- Unplug monitor
```
#0  0x00007f0870385f05 in drm_connector_cleanup (conn=0x55c471171610) at ../backend/drm/drm.c:1076
#1  0x00007f0870385955 in scan_drm_connectors (drm=0x55c470eb0a70) at ../backend/drm/drm.c:969
#2  0x00007f0870381c4b in drm_invalidated (listener=0x55c470eb0b50, data=0x55c470ea8340) at ../backend/drm/backend.c:107
#3  0x00007f08703c921c in wlr_signal_emit_safe (signal=0x55c470eb0210, data=0x55c470ea8340) at ../util/signal.c:29
#4  0x00007f087038dc5d in udev_event (fd=6, mask=1, data=0x55c470ea8340) at ../backend/session/session.c:51
#5  0x00007f0870601a42 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#6  0x00007f087060014c in wl_display_run () at /usr/lib/libwayland-server.so.0
#7  0x000055c4702cc10c in server_run (server=0x55c4705249c0 <server>) at ../sway/server.c:161
#8  0x000055c4702cb95c in main (argc=2, argv=0x7ffce31461e8) at ../sway/main.c:461
```

**Comment by emersion** [comment]
Can't reproduce this crash.
