### ISSUE TITLE
Rootston crash on when client killed with Layer Shell popup

### ISSUE THREAD

**Issue by wmww** [swaywm/wlroots#1408]
To reproduce: Open a layer shell popup, then kill the client with ctrl+C. Rootston crashes because:

First, it destroys the parent layer surface:
```
Thread 1 "rootston" hit Breakpoint 1, 0x00007ffff7915f20 in free () from /home/wmww/code/wlroots/build/rootston/../../../../../../lib64/libc.so.6
#0  0x00007ffff7915f20 in free () at /home/wmww/code/wlroots/build/rootston/../../../../../../lib64/libc.so.6
#1  0x0000555555565049 in handle_destroy (listener=0x55555589c618, data=0x5555558bc4e0) at ../rootston/layer_shell.c:336
#2  0x00007ffff7f96ec6 in wlr_signal_emit_safe (signal=0x5555558bc600, data=0x5555558bc4e0) at ../util/signal.c:29
#3  0x00007ffff7f810d2 in layer_surface_destroy (surface=0x5555558bc4e0) at ../types/wlr_layer_shell_v1.c:182
#4  0x00007ffff7f81609 in handle_surface_destroyed (listener=0x5555558bc5e8, data=0x555555918ff0) at ../types/wlr_layer_shell_v1.c:319
#5  0x00007ffff7f96ec6 in wlr_signal_emit_safe (signal=0x5555559192b0, data=0x555555918ff0) at ../util/signal.c:29
#6  0x00007ffff7f8ee59 in   (resource=0x555555919310) at ../types/wlr_surface.c:584
#7  0x00007ffff7f0ec7f in destroy_resource (element=0x555555919310, data=<optimized out>, flags=0) at src/wayland-server.c:688
#8  0x00007ffff7f13052 in for_each_helper (func=func@entry=0x7ffff7f0ec10 <destroy_resource>, data=data@entry=0x7fffffffe314, entries=<optimized out>, entries=<optimized out>) at src/wayland-util.c:372
#9  0x00007ffff7f1355f in wl_map_for_each (map=0x55555591a7a0, func=0x7ffff7f0ec10 <destroy_resource>, data=0x7fffffffe314) at src/wayland-util.c:385
#10 0x00007ffff7f0edff in wl_client_destroy (client=0x55555591a770) at src/wayland-server.c:847
#11 0x00007ffff7f0eedb in destroy_client_with_error (reason=<optimized out>, client=<optimized out>) at src/wayland-server.c:307
#12 0x00007ffff7f0eedb in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x55555591a770) at src/wayland-server.c:330
#13 0x00007ffff7f10702 in wl_event_loop_dispatch (loop=0x555555582f10, timeout=timeout@entry=-1) at src/event-loop.c:641
#14 0x00007ffff7f0f2ac in wl_display_run (display=0x555555585700) at src/wayland-server.c:1260
#15 0x0000555555565e10 in main (argc=1, argv=0x7fffffffe6d8) at ../rootston/main.c:74
(gdb)  frame 1
#1  0x0000555555565049 in handle_destroy (listener=0x55555589c618, data=0x5555558bc4e0) at ../rootston/layer_shell.c:336
warning: Source file is more recent than executable.
336		free(layer);
(gdb) p layer
$1 = (struct roots_layer_surface *) 0x55555589c600
```

Then, it destroys the popup. `popup_handle_unmap` uses the freed parent data, which causes a crash:
```
#0  0x00007ffff7f8535b in wlr_output_layout_get (layout=0x735f6d6f74746f62, reference=0x555555880ea0) at ../types/wlr_output_layout.c:230
#1  0x0000555555567cf2 in output_damage_whole_local_surface (output=0x55555587c860, surface=0x5555559e0f70, ox=123, oy=35, rotation=0) at ../rootston/output.c:647
#2  0x00005555555652a6 in popup_handle_unmap (listener=0x5555559e1408, data=0x5555559e1290) at ../rootston/layer_shell.c:377
#3  0x00007ffff7f96ec6 in wlr_signal_emit_safe (signal=0x5555559e1398, data=0x5555559e1290) at ../util/signal.c:29
#4  0x00007ffff7f75ef9 in unmap_xdg_surface (surface=0x5555559e1290) at ../types/xdg_shell/wlr_xdg_surface.c:34
#5  0x00007ffff7f76e38 in destroy_xdg_surface (surface=0x5555559e1290) at ../types/xdg_shell/wlr_xdg_surface.c:465
#6  0x00007ffff7f758d0 in xdg_client_handle_resource_destroy (resource=0x5555559180c0) at ../types/xdg_shell/wlr_xdg_shell.c:71
#7  0x00007ffff7f0ec7f in destroy_resource (element=0x5555559180c0, data=<optimized out>, flags=0) at src/wayland-server.c:688
#8  0x00007ffff7f13052 in for_each_helper (func=func@entry=0x7ffff7f0ec10 <destroy_resource>, data=data@entry=0x7fffffffe314, entries=<optimized out>, entries=<optimized out>) at src/wayland-util.c:372
#9  0x00007ffff7f1355f in wl_map_for_each (map=0x55555591a7a0, func=0x7ffff7f0ec10 <destroy_resource>, data=0x7fffffffe314) at src/wayland-util.c:385
#10 0x00007ffff7f0edff in wl_client_destroy (client=0x55555591a770) at src/wayland-server.c:847
#11 0x00007ffff7f0eedb in destroy_client_with_error (reason=<optimized out>, client=<optimized out>) at src/wayland-server.c:307
#12 0x00007ffff7f0eedb in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x55555591a770) at src/wayland-server.c:330
#13 0x00007ffff7f10702 in wl_event_loop_dispatch (loop=0x555555582f10, timeout=timeout@entry=-1) at src/event-loop.c:641
#14 0x00007ffff7f0f2ac in wl_display_run (display=0x555555585700) at src/wayland-server.c:1260
#15 0x0000555555565e10 in main (argc=1, argv=0x7fffffffe6d8) at ../rootston/main.c:74
```
(The top few stack frames are always a bit different, depending on what is done with the memory post-free)

**Comment by wmww** [comment]
I just tried to reproduce with the layer-shell example, and everything was fine. There must be more factors then just killing a client with a Layer Shell popup. I'll investigate when I have time.

**Comment by panaman67** [comment]
@wmww Can close as rootston is archived?

**Comment by wmww** [comment]
Just verified it doesn't effect Wayfire (the only other wlroots compositor I know that supports layer shell popups), so it was either a rootston-specific issue or has been fixed.
