### ISSUE TITLE
Can't build from AUR: missing `libselinux` dependency

### ISSUE THREAD

**Issue by I60R** [swaywm/wlroots#1477]
I've not had `libselinux` installed and build was failed with the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 111, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 504, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 345, in do_install
    restore_selinux_contexts()
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 159, in restore_selinux_contexts
    subprocess.check_call(['selinuxenabled'])
  File "/usr/lib/python3.7/subprocess.py", line 336, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 317, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'selinuxenabled'
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

After some investigation I've found that I just not have `selinuxenabled` and that it's a part of `libselinux` package. After installing it the problem was gone

**Comment by emersion** [comment]
This is a Meson issue. Can you report this bug to them?
