### ISSUE TITLE
Add multi-seat support to Wayland backend

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/wlroots#1499]
209210d30780ec64995594b77fde3d718b655542
Crash on launch.
```
2019-01-25 20:33:53 - [rootston/config.c:537] No config file found. Using sensible defaults.
2019-01-25 20:33:53 - [backend/wayland/backend.c:186] Creating wayland backend
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_shm v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwp_linux_dmabuf_v1 v3
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_drm v2
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_compositor v4
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_subcompositor v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_data_device_manager v3
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: gamma_control_manager v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwlr_gamma_control_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: gtk_primary_selection_device_manager v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zxdg_output_manager_v1 v2
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: org_kde_kwin_idle v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwp_idle_inhibit_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwlr_layer_shell_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zxdg_shell_v6 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: xdg_wm_base v2
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: org_kde_kwin_server_decoration_manager v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zxdg_decoration_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wp_presentation v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwlr_export_dmabuf_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwlr_screencopy_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwlr_data_control_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwp_virtual_keyboard_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: zwlr_input_inhibit_manager_v1 v1
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_seat v6
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_output v3
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_output v3
2019-01-25 20:33:53 - [backend/wayland/backend.c:65] Remote wayland global: wl_seat v6
rootston: ../backend/wayland/wl_seat.c:425: seat_handle_name: Assertion `backend->seat == wl_seat' failed.
```
```
#0  0x00007f8edf612d7f in raise () at /lib64/libc.so.6
#1  0x00007f8edf5fd672 in abort () at /lib64/libc.so.6
#2  0x00007f8edf5fd548 in _nl_load_domain.cold.0 () at /lib64/libc.so.6
#3  0x00007f8edf60b396 in  () at /lib64/libc.so.6
#4  0x00007f8edfca954f in seat_handle_name (data=0x561ed24ef6a0, wl_seat=0x561ed24f4be0, name=0x561ed24f519c "seat0") at ../backend/wayland/wl_seat.c:425
        backend = 0x561ed24ef6a0
        __PRETTY_FUNCTION__ = "seat_handle_name"
#5  0x00007f8edf0d26d0 in ffi_call_unix64 () at /lib64/libffi.so.6
#6  0x00007f8edf0d20a0 in ffi_call () at /lib64/libffi.so.6
#7  0x00007f8edf52bf5f in  () at /lib64/libwayland-client.so.0
#8  0x00007f8edf5286ca in  () at /lib64/libwayland-client.so.0
#9  0x00007f8edf529c0c in wl_display_dispatch_queue_pending () at /lib64/libwayland-client.so.0
#10 0x00007f8edf52a05c in wl_display_roundtrip_queue () at /lib64/libwayland-client.so.0
#11 0x00007f8edfca6cdc in wlr_wl_backend_create (display=0x561ed24e9700, remote=0x0, create_renderer_func=0x0) at ../backend/wayland/backend.c:214
        wl = 0x561ed24ef6a0
        loop = 0x0
        fd = 0
        events = 0
        config_attribs = {12339, 4, 12324, 1, 12323, 1, 12322, 1, 12321, 1, 12344}
#12 0x00007f8edfc95e22 in attempt_wl_backend (display=0x561ed24e9700, create_renderer_func=0x0) at ../backend/backend.c:92
        backend = 0x7ffd89de7910
        outputs = 0
#13 0x00007f8edfc9658b in wlr_backend_autocreate (display=0x561ed24e9700, create_renderer_func=0x0) at ../backend/backend.c:259
        wl_backend = 0x0
        backend = 0x561ed24ef610
        multi = 0x561ed24ef610
        names = 0x0
        x11_display = 0x0
        libinput = 0x7f8edfc5b5d8 <wl_event_loop_create+72>
        primary_drm = 0x0
#14 0x0000561ed1ee221b in main (argc=1, argv=0x7ffd89de7918) at ../rootston/main.c:24
        __PRETTY_FUNCTION__ = "main"
        socket = 0x0
```
I have two seats in sway currently, one of which is empty:
```
interface: 'wl_seat', version: 6, name: 24
	name: seat0
	capabilities: pointer keyboard
	keyboard repeat rate: 25
	keyboard repeat delay: 600
interface: 'wl_seat', version: 6, name: 27
	name: seat1
	capabilities:
```

**Comment by emersion** [comment]
Yeah, multi-seat support in the Wayland backend is a TODO.
