### ISSUE TITLE
Crash in the RDP backend on RDP window close

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#1654]
The backtrace points to wlroots, happens with both Wayfire and Sway, so most probably a bug in the RDP backend. I just open Sway with the necessary vars for RDP, connect with RDP and close the RDP window:

```
ATTENTION: default value of option vblank_mode overridden by environment.
2019-04-15 19:09:49 - [xwayland/sockets.c:65] Failed to bind socket @/tmp/.X11-unix/X1: Address already in use
2019-04-15 19:09:49 - [xwayland/sockets.c:65] Failed to bind socket @/tmp/.X11-unix/X2: Address already in use
i3status: trying to auto-detect output_format setting
i3status: auto-detected "i3bar"
[19:09:54:169] [8163:8163] [ERROR][com.freerdp.core.transport] - BIO_write returned a system error 32: Broken pipe
[19:09:54:169] [8163:8163] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 0: Success
2019-04-15 19:09:54 - [backend/rdp/peer.c:230] Unable to check client file descriptor for 0x614000002040
=================================================================
==8163==ERROR: AddressSanitizer: attempting double-free on 0x61300006c4c0 in thread T0:
    #0 0x7fa2fe364840 in __interceptor_free (/lib64/libasan.so.5+0xef840)
    #1 0x7fa2fdbb084d in keyboard_destroy ../backend/rdp/keyboard.c:149
    #2 0x7fa2fdbd9ded in wlr_input_device_destroy ../types/wlr_input_device.c:65
    #3 0x7fa2fdbb3004 in rdp_peer_context_free ../backend/rdp/peer.c:282
    #4 0x7fa2fc335f15 in freerdp_peer_context_free (/lib64/libfreerdp2.so.2+0x9ff15)
    #5 0x7fa2fdbb2dcd in rdp_client_activity ../backend/rdp/peer.c:231
    #6 0x7fa2fdc3f2e1 in wl_event_loop_dispatch src/event-loop.c:641
    #7 0x7fa2fdc3de61 in wl_display_run src/wayland-server.c:1260
    #8 0x44516c in server_run ../sway/server.c:216
    #9 0x4417e5 in main ../sway/main.c:398
    #10 0x7fa2fce20412 in __libc_start_main (/lib64/libc.so.6+0x24412)
    #11 0x40d16d in _start (/usr/bin/sway+0x40d16d)

0x61300006c4c0 is located 0 bytes inside of 328-byte region [0x61300006c4c0,0x61300006c608)
freed by thread T0 here:
    #0 0x7fa2fe364840 in __interceptor_free (/lib64/libasan.so.5+0xef840)
    #1 0x7fa2fdbdb380 in wlr_keyboard_destroy ../types/wlr_keyboard.c:142
    #2 0x7fa2fdbd9ceb in wlr_input_device_destroy ../types/wlr_input_device.c:39
    #3 0x7fa2fdbb3004 in rdp_peer_context_free ../backend/rdp/peer.c:282
    #4 0x7fa2fc335f15 in freerdp_peer_context_free (/lib64/libfreerdp2.so.2+0x9ff15)
    #5 0x7fa2fdc3f2e1 in wl_event_loop_dispatch src/event-loop.c:641

previously allocated by thread T0 here:
    #0 0x7fa2fe364e10 in calloc (/lib64/libasan.so.5+0xefe10)
    #1 0x7fa2fdbb0916 in wlr_rdp_keyboard_create ../backend/rdp/keyboard.c:173
    #2 0x7fa2fdbb2669 in xf_peer_activate ../backend/rdp/peer.c:61
    #3 0x7fa2fc319ee5  (/lib64/libfreerdp2.so.2+0x83ee5)

SUMMARY: AddressSanitizer: double-free (/lib64/libasan.so.5+0xef840) in __interceptor_free
==8163==ABORTING
2019-04-15 19:09:54 - [common/ipc-client.c:80] Unable to receive IPC response

=================================================================
==8166==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3840 byte(s) in 6 object(s) allocated from:
    #0 0x7f0ab9df9048 in __interceptor_realloc (/lib64/libasan.so.5+0xf0048)
    #1 0x7f0ab87ee420 in FcPatternObjectInsertElt /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:536

Indirect leak of 6976 byte(s) in 218 object(s) allocated from:
    #0 0x7f0ab9df8c08 in __interceptor_malloc (/lib64/libasan.so.5+0xefc08)
    #1 0x7f0ab87da5af in FcConfigValues /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fccfg.c:1374

Indirect leak of 3522 byte(s) in 285 object(s) allocated from:
    #0 0x7f0ab9d44e60 in strdup (/lib64/libasan.so.5+0x3be60)
    #1 0x7f0ab87edc44 in IA__FcValueSave /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:103

Indirect leak of 3520 byte(s) in 110 object(s) allocated from:
    #0 0x7f0ab9df8e10 in calloc (/lib64/libasan.so.5+0xefe10)
    #1 0x7f0ab87ee9cc in FcValueListCreate /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:136
    #2 0x7f0ab87ee9cc in FcPatternObjectAddWithBinding /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:707

Indirect leak of 2400 byte(s) in 75 object(s) allocated from:
    #0 0x7f0ab9df8e10 in calloc (/lib64/libasan.so.5+0xefe10)
    #1 0x7f0ab87edf0c in FcValueListCreate /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:136
    #2 0x7f0ab87edf0c in FcValueListDuplicate /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:230

Indirect leak of 576 byte(s) in 18 object(s) allocated from:
    #0 0x7f0ab9df8e10 in calloc (/lib64/libasan.so.5+0xefe10)
    #1 0x7f0ab87edd9e in FcValueListCreate /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:136
    #2 0x7f0ab87edd9e in FcValueListPrepend /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fcpat.c:180

Indirect leak of 144 byte(s) in 3 object(s) allocated from:
    #0 0x7f0ab9df8c08 in __interceptor_malloc (/lib64/libasan.so.5+0xefc08)
    #1 0x7f0ab87e7e51 in IA__FcLangSetCreate /usr/src/debug/fontconfig-2.13.1-3.fc29.x86_64/src/fclang.c:476

SUMMARY: AddressSanitizer: 20978 byte(s) leaked in 715 allocation(s).
Exiting due to signal.

```

**Comment by emersion** [comment]
The RDP backend has been dropped.
