### ISSUE TITLE
SIGSEGV in wlr_egl_make_current

### ISSUE THREAD

**Issue by nagisa** [swaywm/wlroots#1855]
When I log-in from lightdm, I occasionally see sway immediately crash in wlroots with the following stacktrace:

```
#0  0x00007f87afe69933 in  () at /usr/lib/libgbm.so.1
#1  0x00007f87a87157fa in  () at /usr/lib/dri/i965_dri.so
#2  0x00007f87a871586d in  () at /usr/lib/dri/i965_dri.so
#3  0x00007f87a7aa6ce7 in  () at /usr/lib/libEGL_mesa.so.0
#4  0x00007f87a7a964ee in  () at /usr/lib/libEGL_mesa.so.0
#5  0x00007f87afea26c1 in  () at /usr/lib/libEGL.so.1
#6  0x00007f87b0b7d7f1 in wlr_egl_make_current (egl=0x5650a04e1360, surface=surface@entry=0x0, buffer_age=buffer_age@entry=0x0) at ../render/egl.c:335
#7  0x00007f87b0b7ec61 in gles2_destroy (wlr_renderer=0x5650a0649050) at ../render/gles2/renderer.c:367
#8  0x00007f87b0b6d172 in finish_drm_renderer (renderer=0x5650a04e1350) at ../backend/drm/renderer.c:58
#9  0x00007f87b0b691db in backend_destroy (backend=0x5650a04e1280) at ../backend/drm/backend.c:51
#10 0x00007f87b0b72800 in multi_backend_destroy (wlr_backend=0x5650a04ca1e0) at ../backend/multi/backend.c:54
#11 0x000056509fc29b28 in server_start (server=0x56509fc87e20 <server>) at ../sway/sway/server.c:196
#12 0x000056509fc1e5c5 in main (argc=1, argv=0x7ffe6e5f5528) at ../sway/sway/main.c:387
```

This is likely caused by `surface = NULL`.

Sway and wlroots built a couple of days ago in October 10th from git.

**Comment by manio** [comment]
Hi
Hmmm, it looks a little similar to my backtrace from https://github.com/swaywm/swaybg/issues/12 but in my case the surface is not null...
