### ISSUE TITLE
sway 1.2 freezing (but not crashing) after monitors power back on

### ISSUE THREAD

**Issue by jpeeler** [swaywm/wlroots#1857]
This problem is not easily reproducible, happens about twice a week or so. After the monitors are put to sleep (either directly `swaymsg "output * dpms off"` or in this case indirectly via swayidle) occasionally after trying to resume sway freezes. I've checked and sway has not crashed, but has simply become unresponsive:

$ strace -p 3405
trace: Process 3405 attached
futex(0x55a29053b598, FUTEX_WAIT_PRIVATE, 2, NULL

Debug log gist: https://gist.github.com/jpeeler/d0c5a573b611a292bbaf8fb83c490bf5

The screens just remain powered on, but are just black.

**Comment by ascent12** [comment]
Transferred to wlroots, because I figured it's not directly a sway issue.

Apparently we're calling `eglMakeCurrent` within a callback triggered by `eglMakeCurrent`, which leads to a deadlock inside of Mesa.
I'll have to investigate this more.

**Comment by emersion** [comment]
Can probably fix this by checking if EGL is already current to prevent the infinite loop.

**Comment by ascent12** [comment]
Probably. I might run it by #dri-devel at some point and see if they think it's a Mesa issue by somewhat leaking their internal state without documenting it.

**Comment by emersion** [comment]
Probably fixed by 6bb7639a0f353

**Comment by jpeeler** [comment]
I did not know lock details could be extracted from gdb: 
https://en.wikibooks.org/wiki/Linux_Applications_Debugging_Techniques/Deadlocks

It was not obvious to me from previous comments that this is the case of a lock within the same thread attempting to lock again.

Perhaps this is a mesa issue, mtx_init supports both normal and recursive initialization: https://github.com/mesa3d/mesa/blob/e101af8671a13a8eb8ce714e07294b73a99821cd/include/c11/threads_posix.h#L196

And I kid you not, while typing this report I've now seen kitty lock up and the backtrace is showing egl related calls...

```
[Switching to thread 1 (Thread 0x7f6050fe3ac0 (LWP 2377))]
#0  0x00007f60540f473d in __lll_lock_wait () from /lib64/libpthread.so.0
#2  0x00007f604f172253 in eglMakeCurrent () from /lib64/libEGL_mesa.so.0
#0  0x00007f60540f473d in __lll_lock_wait () at /lib64/libpthread.so.0
#1  0x00007f60540edce9 in pthread_mutex_lock () at /lib64/libpthread.so.0
#2  0x00007f604f172253 in eglMakeCurrent () at /lib64/libEGL_mesa.so.0
#3  0x00007f6053ca8f30 in  () at /lib64/libEGL.so.1
#4  0x00007f60543932d5 in wlr_egl_make_current (egl=0x56104bee4a00, surface=surface@entry=0x0, buffer_age=buffer_age@entry=0x0)
    at ../render/egl.c:335
#5  0x00007f60543954bd in gles2_texture_destroy (wlr_texture=<optimized out>) at ../render/gles2/texture.c:119
#6  0x00007f60543954bd in gles2_texture_destroy (wlr_texture=<optimized out>) at ../render/gles2/texture.c:111
#7  0x00007f6053c6df27 in gbm_bo_destroy () at /lib64/libgbm.so.1
#8  0x00007f604f186cb8 in dri2_drm_destroy_surface () at /lib64/libEGL_mesa.so.0
#9  0x00007f604f182c96 in dri2_make_current () at /lib64/libEGL_mesa.so.0
#10 0x00007f604f17234d in eglMakeCurrent () at /lib64/libEGL_mesa.so.0
#11 0x00007f6053ca8f30 in  () at /lib64/libEGL.so.1
#12 0x00007f60543932d5 in wlr_egl_make_current (egl=0x56104bee4a00, surface=surface@entry=0x0, buffer_age=buffer_age@entry=0x0)
    at ../render/egl.c:335
#13 0x00007f60543954bd in gles2_texture_destroy (wlr_texture=<optimized out>) at ../render/gles2/texture.c:119
#14 0x00007f60543954bd in gles2_texture_destroy (wlr_texture=<optimized out>) at ../render/gles2/texture.c:111
#15 0x00007f6053c6df27 in gbm_bo_destroy () at /lib64/libgbm.so.1
#16 0x00007f604f186cb8 in dri2_drm_destroy_surface () at /lib64/libEGL_mesa.so.0
#17 0x00007f604f176cef in eglDestroySurface () at /lib64/libEGL_mesa.so.0
#18 0x00007f6054393b06 in wlr_egl_destroy_surface (egl=<optimized out>, surface=<optimized out>) at ../render/egl.c:646
#19 0x00007f6054383477 in finish_drm_surface (surf=0x56104bee8208) at ../backend/drm/renderer.c:121
#20 0x00007f6054383477 in finish_drm_surface (surf=0x56104bee8208) at ../backend/drm/renderer.c:109
#21 0x00007f6054380457 in dealloc_crtc (conn=conn@entry=0x56104bff7700) at ../backend/drm/drm.c:976
#22 0x00007f60543805d9 in drm_connector_cleanup (conn=conn@entry=0x56104bff7700) at ../backend/drm/drm.c:1521
#23 0x00007f605438226d in scan_drm_connectors (drm=<optimized out>) at ../backend/drm/drm.c:1333
#24 0x00007f60543c00fc in wlr_signal_emit_safe (signal=<optimized out>, data=data@entry=0x56104bd4f3e0) at ../util/signal.c:29
#25 0x00007f6054389a57 in udev_event (fd=<optimized out>, mask=<optimized out>, data=0x56104bd4f3e0) at ../backend/session/session.c:52
#26 0x00007f605440736a in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#27 0x00007f6054405f25 in wl_display_run () at /lib64/libwayland-server.so.0
#28 0x000056104b3db46d in main (argc=1, argv=0x7ffdeb7a3e28) at ../sway/main.c:400
#1  0x00007f60540edce9 in pthread_mutex_lock () from /lib64/libpthread.so.0
rax            0xfffffffffffffe00  -512
rbx            0x0                 0
rcx            0x7f60540f473d      140051703875389
rdx            0x0                 0
rsi            0x80                128
rdi            0x56104bf51c08      94627993820168
rbp            0x56104bee5440      0x56104bee5440
rsp            0x7ffdeb7a3500      0x7ffdeb7a3500
r8             0x56104bf51c08      94627993820168
r9             0x0                 0
r10            0x1                 1
r11            0x202               514
r12            0x0                 0
r13            0x0                 0
r14            0x56104bf51c00      94627993820160
r15            0x56104bf51c08      94627993820168
rip            0x7f60540edce9      0x7f60540edce9 <pthread_mutex_lock+89>
eflags         0x202               [ IF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
The directory where separate debug symbols are searched for is "/usr/lib/debug".
$1 = 2
$2 = 0
$3 = 2377
$4 = 2377
Detaching from program: /usr/bin/sway, process 2377
[Inferior 1 (process 2377) detached]
```
Apparently the gdb commands aren't captured here and I already rebooted after the last deadlock, but I think everyone gets the idea.

**Comment by jpeeler** [comment]
Is it possible that wlroots actually is an issue here? This is some backtrace output from a stuck kitty:

(gdb) bt
#0  0x00007fae94d393c5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fae85982e73 in wl_display_read_events () from /lib64/libwayland-client.so.0
#2  0x00007fae85983649 in wl_display_dispatch_queue () from /lib64/libwayland-client.so.0
#3  0x00007fae84ee2b1c in dri2_wl_swap_buffers_with_damage () from /lib64/libEGL_mesa.so.0
#4  0x00007fae84ed1ef6 in eglSwapBuffers () from /lib64/libEGL_mesa.so.0
#5  0x00007fae859dabe7 in swapBuffersEGL (window=0x379e420) at glfw/egl_context.c:232
#6  0x00007fae859c92b3 in glfwSwapBuffers (handle=<error reading variable: DW_FORM_strp pointing outside of .debug_str section [in module /usr/lib/debug/usr/lib64/kitty/kitty/fast_data_types.so-0.14.6-12.fc30.x86_64.debug]>) at glfw/context.c:657
