### ISSUE TITLE
segfault in wlr_egl_swap_buffers

### ISSUE THREAD

**Issue by sanga** [swaywm/wlroots#1869]
Sorry, I don't have nice repro steps for this. The thing I noticed at the time when this happened was that CPU went to 100% and there was a lot of memory pressure too. Then the screen started flickering black and then Sway came down and kicked me back to GDM.

version info

```
sway version 1.2-fa0abaf7 (Oct 22 2019, branch 'master')
wlroots=d113e48a2a32542fe6e12f1759f07888364609bf
```

```
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7fd747f433 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
[Current thread is 1 (Thread 0x7f7fd7d7e9c0 (LWP 18679))]
#0  0x00007f7fd747f433 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#1  0x00007f7fd747f6f8 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007f7fd747f7c1 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007f7fd7480154 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007f7fd64fe5dd in  () at /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0
#5  0x00007f7fd64efb96 in eglSwapBuffers () at /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0
#6  0x00007f7fd94f9971 in wlr_egl_swap_buffers (egl=0x55e972f0aab0, surface=0x55e973218010, damage=0x55e9730eeab8) at ../render/egl.c:398
        ret = 32767
#7  0x00007f7fd94e4349 in swap_drm_surface_buffers (surf=0x55e972f1d538, damage=0x55e9730eeab8) at ../backend/drm/renderer.c:151
#8  0x00007f7fd94dfa19 in drm_connector_commit (output=0x55e9730ee990) at ../backend/drm/drm.c:359
        conn = 0x55e9730ee990
        drm = 0x55e972f0a9d0
        crtc = 0x55e972f1cd78
        plane = 0x55e972f1d530
        damage = 0x55e9730eeab8
        bo = 0x0
        fb_id = 0
        __PRETTY_FUNCTION__ = "drm_connector_commit"
#9  0x00007f7fd9529e94 in wlr_output_commit (output=0x55e9730ee990) at ../types/wlr_output.c:484
        now = {tv_sec = 26105, tv_nsec = 316142726}
        event = {output = 0x55e9730ee990, when = 0x7fff52d28290}
        cursor = 0x87000000f00
#10 0x000055e971dcf21a in output_render (output=0x55e973217c80, when=0x7fff52d283e0, damage=0x7fff52d283f0) at ../sway/desktop/render.c:1063
        wlr_output = 0x55e9730ee990
        renderer = 0x55e97309c080
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x55e97355f100
        fullscreen_con = 0x0
        seat = 0x55e9730b0720
        focus = 0x55e973558930
        width = 3840
        height = 2160
        frame_damage = {extents = {x1 = 0, y1 = 2135, x2 = 3840, y2 = 2160}, data = 0x0}
        transform = WL_OUTPUT_TRANSFORM_NORMAL
#11 0x000055e971dcaf4f in damage_handle_frame (listener=0x55e973217e08, data=0x55e973217e40) at ../sway/desktop/output.c:529
        output = 0x55e973217c80
        now = {tv_sec = 26104, tv_nsec = 304395575}
        workspace = 0x55e97355f100
        fullscreen_con = 0x0
        needs_frame = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 3840, y2 = 2160}, data = 0x0}
#12 0x00007f7fd9539aa2 in wlr_signal_emit_safe (signal=0x55e973217ea0, data=0x55e973217e40) at ../util/signal.c:29
        pos = 0x55e973217e08
        l = 0x55e973217e08
        cursor = {link = {prev = 0x55e973217e08, next = 0x7fff52d28460}, notify = 0x7f7fd95399ec <handle_noop>}
        end = {link = {prev = 0x7fff52d28440, next = 0x55e973217ea0}, notify = 0x7f7fd95399ec <handle_noop>}
#13 0x00007f7fd9524960 in output_handle_frame (listener=0x55e973217f38, data=0x55e9730ee990) at ../types/wlr_output_damage.c:51
        output_damage = 0x55e973217e40
#14 0x00007f7fd9539aa2 in wlr_signal_emit_safe (signal=0x55e9730eeae0, data=0x55e9730ee990) at ../util/signal.c:29
        pos = 0x55e973217f38
        l = 0x55e973217f38
        cursor = {link = {prev = 0x55e973217f38, next = 0x7fff52d28500}, notify = 0x7f7fd95399ec <handle_noop>}
        end = {link = {prev = 0x7fff52d284e0, next = 0x55e9730eeae0}, notify = 0x7f7fd95399ec <handle_noop>}
#15 0x00007f7fd952a10c in wlr_output_send_frame (output=0x55e9730ee990) at ../types/wlr_output.c:538
#16 0x00007f7fd94e311e in page_flip_handler (fd=9, seq=1565194, tv_sec=26104, tv_usec=304805, crtc_id=65, data=0x55e972f0a9d0) at ../backend/drm/drm.c:1431
        drm = 0x55e972f0a9d0
        conn = 0x55e9730ee990
        search = 0x55e972f0a7e0
        present_flags = 7
        present_time = {tv_sec = 26104, tv_nsec = 304805000}
        present_event = {output = 0x55e9730ee990, when = 0x7fff52d28590, seq = 1565194, refresh = 16667500, flags = 7}
#17 0x00007f7fd87f6d57 in drmHandleEvent () at /usr/lib/x86_64-linux-gnu/libdrm.so.2
#18 0x00007f7fd94e31a3 in handle_drm_event (fd=9, mask=1, data=0x0) at ../backend/drm/drm.c:1441
        event = {version = 3, vblank_handler = 0x0, page_flip_handler = 0x0, page_flip_handler2 = 0x7f7fd94e2ee5 <page_flip_handler>, sequence_handler = 0x0}
#19 0x00007f7fd9581942 in wl_event_loop_dispatch () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#20 0x00007f7fd958056a in wl_display_run () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#21 0x000055e971dc6ccf in server_run (server=0x55e971e30fa0 <server>) at ../sway/server.c:205
#22 0x000055e971dc62e7 in main (argc=1, argv=0x7fff52d28dd8) at ../sway/main.c:402
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x55e971e16008 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55e971e1600d "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55e971e16014 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55e971e1601d "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55e971e16023 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55e971e1602b "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55e971e16033 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55e971e16042 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55e971e16052 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55e971e15ae0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

It would appear that this bug has been introduced since:

```
sway: 53e01bf5c7763b5f49ce15b05f6b32f986e2b2ba
wlroots: 734c64a6cc005f2c20df48af8079538a8c4cbd39
```

Or to be more precise, I was running those earlier versions just fine up until I upgraded this morning to the newer version and then had a crash within 5 or 6 hours

**Comment by sanga** [comment]
So I've struck this a couple more times and some more info is:

- appears to also happen towards the end of the work day
- swaybar starts using a lot of cpu just before the crash

A resource leak in swaybar is maybe causing this? (I'll try to investigate that avenue next time this pops up)

**Comment by sanga** [comment]
I haven't encountered this since updating to b81bb2ef. So it would appear that this has been fixed. Apparently by something between d113e48a and b81bb2ef
