### ISSUE TITLE
Segfault in render_surface with X11 clients

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#205]
Wayland backend.

```
#0  0x00007f7591b12cfa in __strcmp_sse2_unaligned () at /usr/lib/libc.so.6
#1  0x00007f7592087325 in  () at /usr/lib/libwayland-server.so.0
#2  0x00007f75920821c5 in wl_resource_instance_of () at /usr/lib/libwayland-server.so.0
#3  0x00007f7592083f9d in wl_shm_buffer_get () at /usr/lib/libwayland-server.so.0
#4  0x00007f75922c0449 in wl_keyboard_send_modifiers (resource_=0x3e9bfa057aa21e00, serial=21986, mods_depressed=0, mods_latched=0, mods_locked=0, group=0)
    at /usr/include/wayland-server-protocol.h:3678
#5  0x000055e291105960 in render_surface (surface=0x55e292318860, desktop=0x55e292130790, wlr_output=0x55e29229be90, when=0x7fffb2941048, lx=21, ly=18) at ../rootston/output.c:22
#6  0x000055e291105903 in render_view (view=0x55e29230f7c0, desktop=0x55e292130790, wlr_output=0x55e29229be90, when=0x7fffb2941048) at ../rootston/output.c:58
#7  0x000055e291105721 in output_frame_notify (listener=0x55e2923054f0, data=0x55e29229be90) at ../rootston/output.c:76
#8  0x00007f75922af70b in  () at /usr/include/wayland-client-protocol.h:3526
#9  0x000055e29229bf70 in  ()
#10 0x000055e2923054f0 in  ()
#11 0x000055e29229be90 in  ()
#12 0x000055e29229bf70 in  ()
#13 0x00007fffb29410c0 in  ()
#14 0x00007f75922b02e3 in xdg_toplevel_handle_close (data=0x55e29229bf70, xdg_toplevel=0x55e29229be90) at ../backend/wayland/output.c:199
```

Another one:

```
#0  0x00007ffff7408cfa in __strcmp_sse2_unaligned () at /usr/lib/libc.so.6
#1  0x00007ffff797d325 in  () at /usr/lib/libwayland-server.so.0
#2  0x00007ffff79781c5 in wl_resource_instance_of () at /usr/lib/libwayland-server.so.0
#3  0x00007ffff7979f9d in wl_shm_buffer_get () at /usr/lib/libwayland-server.so.0
#4  0x00007ffff7bb6549 in wlr_surface_flush_damage (surface=0x5555560ae1a0) at ../types/wlr_surface.c:425
#5  0x000055555555b960 in render_surface (surface=0x5555560ae1a0, desktop=0x555555f5e960, wlr_output=0x5555560493a0, when=0x7fffffffe098, lx=21, ly=18)
    at ../rootston/output.c:22
#6  0x000055555555b903 in render_view (view=0x5555560a1360, desktop=0x555555f5e960, wlr_output=0x5555560493a0, when=0x7fffffffe098) at ../rootston/output.c:58
#7  0x000055555555b721 in output_frame_notify (listener=0x5555560a21d0, data=0x5555560493a0) at ../rootston/output.c:76
#8  0x00007ffff7ba580b in wl_signal_emit (signal=0x555556049480, data=0x5555560493a0) at /usr/include/wayland-server-core.h:388
#9  0x00007ffff7ba63e3 in surface_frame_callback (data=0x5555560493a0, cb=0x5555560395e0, time=20101480) at ../backend/wayland/output.c:23
#10 0x00007ffff4ae31c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#11 0x00007ffff4ae2c2a in ffi_call () at /usr/lib/libffi.so.6
#12 0x00007ffff7173bad in  () at /usr/lib/libwayland-client.so.0
#13 0x00007ffff7170679 in  () at /usr/lib/libwayland-client.so.0
#14 0x00007ffff71719b4 in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#15 0x00007ffff7ba4da0 in dispatch_events (fd=4, mask=1, data=0x555555770790) at ../backend/wayland/backend.c:20
#16 0x00007ffff797a9b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#17 0x00007ffff797914c in wl_display_run () at /usr/lib/libwayland-server.so.0
#18 0x000055555555b362 in main (argc=1, argv=0x7fffffffe7c8) at ../rootston/main.c:45
```

**Comment by acrisci** [comment]
Can you provide steps to reproduce?

**Comment by emersion** [comment]
I cannot reproduce anymore.
