### ISSUE TITLE
Crash on unplugging tablet

### ISSUE THREAD

**Issue by Xyene** [swaywm/wlroots#2062]
Hi,

I own a Huion 420 tablet. Occasionally, removing it [causes sway to segfault](https://gist.github.com/Xyene/0b13b4c7a64fe406f7b45900b9d31745).

While debugging [an XWayland crash](https://gitlab.freedesktop.org/xorg/xserver/issues/995) on sway that seems to be related to same tablet as well, the maintainer there [also reproduced this issue](https://gitlab.freedesktop.org/xorg/xserver/issues/995#note_432298) (see for backtrace). That thread may contain relevant information to this ticket, like `evemu-describe` output of all the tablet event devices.

Seemingly related, I can trigger a consistent crash in Firefox by plugging in the tablet, hovering over an open Firefox-on-Wayland window with the pen, then while Firefox continues to have focus, unplugging the tablet. I haven't dug into this particular problem yet, but I can probably get some traces if they'd be helpful and relevant.

**Comment by Xyene** [comment]
A trace of Firefox Developer Edition (75, `MOZ_ENABLE_WAYLAND=1`) shows:

```
Thread 1 (Thread 0x7ffff7a9a780 (LWP 5683)):
#0  0x00007ffff56329f1 in g_list_remove () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff65a6df3 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007ffff4ae88ee in ffi_call_unix64 () at /lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007ffff4ae82bf in ffi_call () at /lib/x86_64-linux-gnu/libffi.so.6
#4  0x00007ffff5bb528d in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#5  0x00007ffff5bb1ac9 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#6  0x00007ffff5bb2f94 in wl_display_dispatch_queue_pending () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#7  0x00007ffff65b1884 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007ffff6551940 in gdk_display_get_event () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#9  0x00007ffff65b15a2 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#10 0x00007ffff5636f2e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff56371c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff563725c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007fffefd0646e in  () at /opt/firefox/libxul.so
#14 0x00007fffefd065dd in  () at /opt/firefox/libxul.so
#15 0x00007ffff0196ce2 in  () at /opt/firefox/libxul.so
#16 0x00007fffefbce3a6 in  () at /opt/firefox/libxul.so
#17 0x00007fffefbf8155 in  () at /opt/firefox/libxul.so
#18 0x00007ffff039225f in  () at /opt/firefox/libxul.so
#19 0x00007ffff109bd34 in  () at /opt/firefox/libxul.so
#20 0x00007fffef0e53f3 in  () at /opt/firefox/libxul.so
#21 0x00007ffff168e1fe in  () at /opt/firefox/libxul.so
#22 0x00007ffff169091c in  () at /opt/firefox/libxul.so
#23 0x00007fffef1632af in  () at /opt/firefox/libxul.so
#24 0x00005555555b87a5 in _start ()
```

Not too much information since I don't have debug symbols, but the place where things break down seems to be `libgdk-3`.
