### ISSUE TITLE
Segfault during startup

### ISSUE THREAD

**Issue by progandy** [swaywm/wlroots#2183]
A fresh build of sway and wlroots is crashing during startup. The initial modesetting seems to work and I get a gray screen, then I am back on the terminal.

```WLR_DRM_DEVICES=/dev/dri/card0 sway -d 2>/tmp/debug```

* Version:
sway-git r6353.726d187d-1 (1.4-726d187d)
wlroots-git 0.10.0.r124.gf72686c0-1

* Debug Log: [debug.log](https://github.com/swaywm/wlroots/files/4606746/debug.log)
* Configuration File: default
* Stack Trace: [trace.txt](https://github.com/swaywm/wlroots/files/4606751/trace.txt)

A slightly older build starts fine:
wlroots-git-0.10.0.r89.ge51d5077
sway-git-r6323.5cf5349c

**Comment by emersion** [comment]
```
Program terminated with signal SIGSEGV, Segmentation fault.
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x00007fb6bd778871 in drm_fb_clear (fb=fb@entry=0x70)
    at ../backend/drm/renderer.c:247
247		switch (fb->type) {
[Current thread is 1 (Thread 0x7fb6bca3c940 (LWP 194553))]
(gdb) bt full
#0  0x00007fb6bd778871 in drm_fb_clear (fb=fb@entry=0x70)
    at ../backend/drm/renderer.c:247
        __PRETTY_FUNCTION__ = "drm_fb_clear"
#1  0x00007fb6bd778e72 in drm_fb_move (new=0x70, old=0x48)
    at ../backend/drm/renderer.c:357
#2  0x00007fb6bd775043 in drm_crtc_page_flip (conn=0x562a216e99c0)
    at ../backend/drm/drm.c:362
        crtc = <optimized out>
        __PRETTY_FUNCTION__ = "drm_crtc_page_flip"
#3  0x00007fb6bd775470 in drm_connector_init_renderer
    (conn=conn@entry=0x562a216e99c0, mode=mode@entry=0x562a2168e000)
    at ../backend/drm/drm.c:775
        drm = 0x562a20e81bf0
        crtc = <optimized out>
        plane = <optimized out>
        width = 1366
        height = 768
        format = 875713089
        modifiers = true
        no_modifiers = <optimized out>
#4  0x00007fb6bd775824 in drm_connector_set_mode
    (output=output@entry=0x562a216e99c0, wlr_mode=0x562a2168e000)
    at ../backend/drm/drm.c:864
        conn = 0x562a216e99c0
        drm = <optimized out>
        mode = 0x562a2168e000
--Type <RET> for more, q to quit, c to continue without paging--
#5  0x00007fb6bd7765a0 in drm_connector_commit (output=0x562a216e99c0)
    at ../backend/drm/drm.c:527
        drm = 0x562a20e81bf0
#6  0x00007fb6bd7a84b3 in wlr_output_commit (output=output@entry=0x562a216e99c0)
    at ../types/wlr_output.c:578
        now = {tv_sec = 593643, tv_nsec = 986326885}
        event = {output = 0x562a216e99c0, when = 0x7fff5fffdc20}
        scale_updated = <optimized out>
        geometry_updated = <optimized out>
#7  0x0000562a1f4dad5a in apply_output_config
    (oc=oc@entry=0x562a21663140, output=output@entry=0x562a216ea2f0)
    at ../sway/sway/config/output.c:419
        wlr_output = 0x562a216e99c0
        was_enabled = false
        output_box = <optimized out>
        input_device = <optimized out>
#8  0x0000562a1f4c61ad in handle_new_output
    (listener=0x562a1f520ee0 <server+96>, data=0x562a216e99c0)
    at ../sway/sway/desktop/output.c:951
        server = 0x562a1f520e80 <server>
        wlr_output = 0x562a216e99c0
        output = 0x562a216ea2f0
        oc = 0x562a21663140
#9  0x00007fb6bd7b3cee in wlr_signal_emit_safe
    (signal=<optimized out>, data=0x562a216e99c0) at ../util/signal.c:29
        pos = 0x562a1f520ee0 <server+96>
--Type <RET> for more, q to quit, c to continue without paging--
        l = 0x562a1f520ee0 <server+96>
        cursor = 
          {link = {prev = 0x562a1f520ee0 <server+96>, next = 0x7fff5fffdd10}, notify = 0x7fb6bd7b3c60 <handle_noop>}
        end = 
          {link = {prev = 0x7fff5fffdcf0, next = 0x562a20e7b2f8}, notify = 0x7fb6bd7b3c60 <handle_noop>}
#10 0x00007fb6bd7b3cee in wlr_signal_emit_safe
    (signal=signal@entry=0x562a20e81c18, data=data@entry=0x562a216e99c0)
    at ../util/signal.c:29
        pos = 0x562a214842e8
        l = 0x562a214842e8
        cursor = 
          {link = {prev = 0x562a214842e8, next = 0x7fff5fffdd80}, notify = 0x7fb6bd7b3c60 <handle_noop>}
        end = 
          {link = {prev = 0x7fff5fffdd60, next = 0x562a20e81c18}, notify = 0x7fb6bd7b3c60 <handle_noop>}
#11 0x00007fb6bd77714d in scan_drm_connectors (drm=<optimized out>)
    at ../backend/drm/drm.c:1522
        conn = 0x562a216e99c0
        i = 0
        res = <optimized out>
        seen_len = 0
        seen = 0x7fff5fffddf0
        new_outputs_len = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        new_outputs = 0x7fff5fffddd0
        conn = <optimized out>
        tmp_conn = <optimized out>
        index = <optimized out>
#12 0x00007fb6bd7739a3 in backend_start (backend=<optimized out>)
    at ../backend/drm/backend.c:26
        drm = <optimized out>
#13 0x00007fb6bd77e626 in multi_backend_start (wlr_backend=0x562a20e7b2d0)
    at ../backend/multi/backend.c:31
        backend = 0x562a20e7b2d0
        sub = 0x562a214842c0
#14 0x0000562a1f4c1e89 in server_start (server=0x562a1f520e80 <server>)
    at ../sway/sway/server.c:214
```

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2185?

**Comment by progandy** [comment]
> Can you try #2185?

That works, thanks.
