### ISSUE TITLE
Swayidle turning off monitors crashes sway when kanshi is running

### ISSUE THREAD

**Issue by TimoFreiberg** [swaywm/wlroots#2199]
* Sway Version: `sway version 1.4-9b5895be (May 15 2020, branch 'master')`

* Debug Log, Configuration File, backtrace: https://gist.github.com/TimoFreiberg/d91047729448a47c6582886b8821cf6b

Steps: Log in and wait for swayidle to turn off the display

When kanshi is not running, it seems to work fine.

**Comment by Xyene** [comment]
Thanks, this looks like a wlroots issue, transferring the issue over there.

The stack trace looks very similar to the one from https://github.com/swaywm/wlroots/issues/1867, but with a different assertion failing (/cc @emersion).

**Comment by emersion** [comment]
```
#0  0x00007f30a45282e5 in raise () at /usr/lib/libc.so.6
#1  0x00007f30a4511853 in abort () at /usr/lib/libc.so.6
#2  0x00007f30a4511727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007f30a4520936 in  () at /usr/lib/libc.so.6
#4  0x00007f30a478bc10 in head_send_state (head=0x5567452d1390, head_resource=0x5567451d74e0, state=31) at protocol/wlr-output-management-unstable-v1-protocol.h:453
        found = <optimized out>
        mode_resource = <optimized out>
        client = 0x5567451d5f70
        __PRETTY_FUNCTION__ = "head_send_state"
#5  0x00007f30a478cfbb in wlr_output_manager_v1_set_configuration (manager=0x556744b006e0, config=0x556744f9f070) at ../types/wlr_output_management_v1.c:854
        head = 0x5567452d1390
        manager_resource = 0x5567451d3a50
        changed = false
        existing_head = <optimized out>
        head_tmp = <optimized out>
        config_head = <optimized out>
        config_head_tmp = 0x556744f9f030
        manager_resource = <optimized out>
#6  0x00007f30a479b36e in wlr_signal_emit_safe (signal=signal@entry=0x556744afec88, data=data@entry=0x556744afec60) at ../util/signal.c:29
        pos = 0x556742f22f38 <server+120>
        l = 0x556742f22f38 <server+120>
        cursor = {link = {prev = 0x556742f22f38 <server+120>, next = 0x556744afff00}, notify = 0x7f30a479b2e0 <handle_noop>}
        end = {link = {prev = 0x556744b02508, next = 0x556744afec88}, notify = 0x7f30a479b2e0 <handle_noop>}
#7  0x00007f30a478a6cf in output_layout_reconfigure (layout=layout@entry=0x556744afec60) at ../types/wlr_output_layout.c:130
        max_x = <optimized out>
        max_x_y = <optimized out>
        l_output = <optimized out>
```

**Comment by kennylevinsen** [comment]
I'm hitting this *relatively* often. Some more debug:

```gdb
(gdb) bt full
#0  0x00007f885fbb3615 in raise () at /usr/lib/libc.so.6
#1  0x00007f885fb9c862 in abort () at /usr/lib/libc.so.6
#2  0x00007f885fb9c747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007f885fbabbf6 in  () at /usr/lib/libc.so.6
#4  0x00007f885fe1dcf8 in head_send_state (head=0x5619b085aca0, head_resource=0x5619b06dfb60, state=<optimized out>) at ../types/wlr_output_management_v1.c:696
        found = <optimized out>
        mode_resource = <optimized out>
        client = 0x5619b07973c0
        __PRETTY_FUNCTION__ = "head_send_state"
#5  0x00007f885fe1f12f in manager_update_head (manager=0x5619aff64350, next=0x5619b088f460, head=0x5619b085aca0) at ../types/wlr_output_management_v1.c:847
        resource = 0x5619b06dfb60
        current = 0x5619b085aca0
        state = <optimized out>
        mode = <optimized out>
        updated_head = 0x5619b088f460
        changed = <optimized out>
        existing_head = 0x5619b085aca0
        head_tmp = 0x5619b06627c0
        config_head = <optimized out>
        config_head_tmp = <optimized out>
        manager_resource = <optimized out>
#6  wlr_output_manager_v1_set_configuration (manager=0x5619aff64350, config=0x5619b08443a0) at ../types/wlr_output_management_v1.c:865
        updated_head = 0x5619b088f460
        changed = <optimized out>
        existing_head = 0x5619b085aca0
        head_tmp = 0x5619b06627c0
        config_head = <optimized out>
        config_head_tmp = <optimized out>
        manager_resource = <optimized out>
#7  0x00007f885fe3012e in wlr_signal_emit_safe (signal=<optimized out>, data=0x5619b062edf0) at ../util/signal.c:29
        pos = 0x5619af171f60 <server+96>
        l = 0x5619af171f60 <server+96>
        cursor = {link = {prev = 0x5619af171f60 <server+96>, next = 0x7fffd2014cb0}, notify = 0x7f885fe300a0 <handle_noop>}
        end = {link = {prev = 0x7fffd2014c90, next = 0x5619af6aa7b8}, notify = 0x7f885fe300a0 <handle_noop>}
#8  0x00007f885fe3012e in wlr_signal_emit_safe (signal=signal@entry=0x5619af6bc808, data=data@entry=0x5619b062edf0) at ../util/signal.c:29
        pos = 0x5619aff48eb8
        l = 0x5619aff48eb8
        cursor = {link = {prev = 0x5619aff48eb8, next = 0x7fffd2014d20}, notify = 0x7f885fe300a0 <handle_noop>}
        end = {link = {prev = 0x7fffd2014d00, next = 0x5619af6bc808}, notify = 0x7f885fe300a0 <handle_noop>}
#9  0x00007f885fdef328 in scan_drm_connectors (drm=<optimized out>) at ../backend/drm/drm.c:1453
        conn = 0x5619b062edf0
        i = 0
        res = <optimized out>
        seen_len = 3
        seen = 0x7fffd2014d90
        new_outputs_len = <optimized out>
        new_outputs = 0x7fffd2014d70
        conn = <optimized out>
        tmp_conn = <optimized out>
        index = <optimized out>
#10 0x00007f885fe3012e in wlr_signal_emit_safe (signal=signal@entry=0x5619af69fcd0, data=data@entry=0x0) at ../util/signal.c:29
        pos = 0x5619af6bc8c8
        l = 0x5619af6bc8c8
        cursor = {link = {prev = 0x5619af6bc8c8, next = 0x7fffd2014f10}, notify = 0x7f885fe300a0 <handle_noop>}
        end = {link = {prev = 0x7fffd2014ef0, next = 0x5619af69fcd0}, notify = 0x7f885fe300a0 <handle_noop>}
#11 0x00007f885fe004bb in handle_udev_event (fd=<optimized out>, mask=<optimized out>, data=0x5619af6aa820) at ../backend/session/session.c:93
        devnum = <optimized out>
        dev = 0x5619af69fcb0
        session = 0x5619af6aa820
        udev_dev = 0x5619b06e5950
        sysname = 0x5619b0856230 "card0"
        devnode = <optimized out>
        action = <optimized out>
        seat = <optimized out>
        __PRETTY_FUNCTION__ = "handle_udev_event"
#12 0x00007f885fe81faa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#13 0x00007f885fe804e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#14 0x00005619af10b302 in server_run (server=<optimized out>) at ../sway-pr-git/sway/server.c:247
#15 0x00005619af0ff633 in main (argc=2, argv=0x7fffd2015358) at ../sway-pr-git/sway/main.c:431
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x5619af152464 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5619af155d89 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5619af152469 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5619af152472 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5619af1523c8 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5619af1514b1 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5619af152478 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5619af152487 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5619af152497 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5619af152808 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>

(gdb) f 4
#4  0x00007f885fe1dcf8 in head_send_state (head=0x5619b085aca0, head_resource=0x5619b06dfb60, state=<optimized out>) at ../types/wlr_output_management_v1.c:696
696                     assert(head->state.mode != NULL ||
(gdb) p *head
$12 = {state = {output = 0x5619b062edf0, enabled = true, mode = 0x0, custom_mode = {width = 0, height = 0, refresh = 0}, x = 3840, y = 0, 
    transform = WL_OUTPUT_TRANSFORM_NORMAL, scale = 1}, manager = 0x5619aff64350, link = {prev = 0x5619aff64370, next = 0x5619b0662800}, resources = {prev = 0x5619b06dfb80, 
    next = 0x5619b06dfb80}, mode_resources = {prev = 0x5619b06dfaf0, next = 0x5619b073d330}, output_destroy = {link = {prev = 0x5619b08882e8, next = 0x5619b088f4b8}, 
    notify = 0x7f885fe1da00 <head_handle_output_destroy>}}

(gdb) f 6
#6  wlr_output_manager_v1_set_configuration (manager=0x5619aff64350, config=0x5619b08443a0) at ../types/wlr_output_management_v1.c:865
865                             changed |= manager_update_head(manager,
(gdb) list
860             struct wlr_output_head_v1 *existing_head, *head_tmp;
861             wl_list_for_each_safe(existing_head, head_tmp, &manager->heads, link) {
862                     struct wlr_output_configuration_head_v1 *updated_head =
863                             configuration_get_head(config, existing_head->state.output);
864                     if (updated_head != NULL) {
865                             changed |= manager_update_head(manager,
866                                     existing_head, &updated_head->state);
867                             config_head_destroy(updated_head);
868                     } else {
869                             head_destroy(existing_head);
(gdb) p *updated_head
$13 = {state = {output = 0x5619b062edf0, enabled = true, mode = 0x0, custom_mode = {width = 0, height = 0, refresh = 0}, x = 3840, y = 0, 
    transform = WL_OUTPUT_TRANSFORM_NORMAL, scale = 1}, config = 0x5619b08443a0, link = {prev = 0x5619b088de50, next = 0x5619b08443a0}, resource = 0x0, output_destroy = {
    link = {prev = 0x5619b085ad10, next = 0x5619b062f018}, notify = 0x7f885fe1e640 <config_head_handle_output_destroy>}}

(gdb) f 9
#9  0x00007f885fdef328 in scan_drm_connectors (drm=<optimized out>) at ../backend/drm/drm.c:1453
1453                    wlr_signal_emit_safe(&drm->backend.events.new_output,
(gdb) list
1448
1449            for (size_t i = 0; i < new_outputs_len; ++i) {
1450                    struct wlr_drm_connector *conn = new_outputs[i];
1451
1452                    wlr_drm_conn_log(conn, WLR_INFO, "Requesting modeset");
1453                    wlr_signal_emit_safe(&drm->backend.events.new_output,
1454                            &conn->output);
1455            }
1456
1457            attempt_enable_needs_modeset(drm);
(gdb) p *conn
$14 = {output = {impl = 0x7f885fe6c5c0 <output_impl>, backend = 0x5619af6bc7e0, display = 0x5619af6aa6b0, global = 0x0, resources = {prev = 0x5619b062ee10, 
      next = 0x5619b062ee10}, name = "DP-1", '\000' <repeats 19 times>, description = 0x5619b0892c10 "Goldstar Company Ltd LG Ultra HD 0x00003200 (DP-1)", 
    make = "Goldstar Company Ltd", '\000' <repeats 35 times>, model = "LG Ultra HD\000 \000\000", serial = "0x00003200\000\000\000\000\000", phys_width = 600, 
    phys_height = 340, modes = {prev = 0x5619b0876770, next = 0x5619b05f1d90}, current_mode = 0x0, width = 0, height = 0, refresh = 0, enabled = false, scale = 1, 
    subpixel = WL_OUTPUT_SUBPIXEL_UNKNOWN, transform = WL_OUTPUT_TRANSFORM_NORMAL, adaptive_sync_status = WLR_OUTPUT_ADAPTIVE_SYNC_DISABLED, needs_frame = true, 
    frame_pending = false, transform_matrix = {0, 0, 0, 0, 0, 0, 0, 0, 0}, pending = {committed = 0, damage = {extents = {x1 = 0, y1 = 0, x2 = 0, y2 = 0}, 
        data = 0x7f885ff1a4f0}, enabled = false, scale = 0, transform = WL_OUTPUT_TRANSFORM_NORMAL, adaptive_sync_enabled = false, 
      buffer_type = WLR_OUTPUT_STATE_BUFFER_RENDER, buffer = 0x0, mode_type = WLR_OUTPUT_STATE_MODE_FIXED, mode = 0x0, custom_mode = {width = 0, height = 0, refresh = 0}, 
      gamma_lut = 0x0, gamma_lut_size = 0}, commit_seq = 1, events = {frame = {listener_list = {prev = 0x5619b0893968, next = 0x5619b0893968}}, damage = {listener_list = {
          prev = 0x5619b0893950, next = 0x5619b0893950}}, needs_frame = {listener_list = {prev = 0x5619b0893938, next = 0x5619b0893938}}, precommit = {listener_list = {
          prev = 0x5619b0893980, next = 0x5619b0893980}}, commit = {listener_list = {prev = 0x5619b08882d0, next = 0x5619b0893998}}, present = {listener_list = {
          prev = 0x5619b00cef20, next = 0x5619b00cef20}}, bind = {listener_list = {prev = 0x5619b062efd8, next = 0x5619b062efd8}}, enable = {listener_list = {
          prev = 0x5619b062efe8, next = 0x5619b062efe8}}, mode = {listener_list = {prev = 0x5619b08882b8, next = 0x5619b0893920}}, description = {listener_list = {
          prev = 0x5619b089d968, next = 0x5619b089d968}}, destroy = {listener_list = {prev = 0x5619b088f4b8, next = 0x5619b0893908}}}, idle_frame = 0x5619b08ab880, 
    idle_done = 0x5619b085adf0, attach_render_locks = 0, cursors = {prev = 0x5619b06de0d0, next = 0x5619b06de0d0}, hardware_cursor = 0x0, software_cursor_locks = 0, 
    display_destroy = {link = {prev = 0x5619b062f380, next = 0x5619af6aa718}, notify = 0x7f885fe1ffa0 <handle_display_destroy>}, data = 0x5619b00cedd0}, 
  backend = 0x5619af6bc7e0, name = "DP-1", '\000' <repeats 19 times>, state = WLR_DRM_CONN_NEEDS_MODESET, desired_mode = 0x0, desired_enabled = true, id = 103, 
  crtc = 0x5619af6acb70, possible_crtcs = 7, props = {{edid = 1, dpms = 2, link_status = 5, path = 0, vrr_capable = 0, subconnector = 107, crtc_id = 20}, props = {1, 2, 5, 
      0}}, cursor_x = -487, cursor_y = 1416, old_crtc = 0x5619b05d87f0, link = {prev = 0x5619b062c470, next = 0x5619b062f410}, pending_page_flip_crtc = 0}
```
