### ISSUE TITLE
Crash after 2072d59d

### ISSUE THREAD

**Issue by TheAvidDev** [swaywm/wlroots#2388]
With [this commit](https://github.com/swaywm/wlroots/commit/2072d59da54ac772410271ad2219ca107a7fff48) applied, I get the following crash when spawning an Alacritty window in Sway.
```
#0  0x00007f86a8dc8880 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x0000556bc958c62f in wl_signal_add (signal=0x556bcc028a78, listener=0x556bcc114868) at /usr/include/wayland-server-core.h:441
#2  0x0000556bc958d939 in handle_map (listener=0x556bcc114898, data=0x556bcc1143f0) at ../sway/desktop/xdg_shell.c:485
        xdg_shell_view = 0x556bcc1146c0
        view = 0x556bcc1146c0
        xdg_surface = 0x556bcc1143f0
        csd = false
#3  0x00007f86a8d7584e in wlr_signal_emit_safe (signal=signal@entry=0x556bcc1144e8, data=data@entry=0x556bcc1143f0) at ../util/signal.c:29
        pos = 0x556bcc114898
        l = 0x556bcc114898
        cursor = {link = {prev = 0x556bcc114898, next = 0x7fffacebe720}, notify = 0x7f86a8d757c0 <handle_noop>}
        end = {link = {prev = 0x7fffacebe700, next = 0x556bcc1144e8}, notify = 0x7f86a8d757c0 <handle_noop>}
#4  0x00007f86a8d551ba in handle_xdg_surface_commit (wlr_surface=<optimized out>) at ../types/xdg_shell/wlr_xdg_surface.c:381
        surface = 0x556bcc1143f0
        __PRETTY_FUNCTION__ = "handle_xdg_surface_commit"
#5  0x00007f86a8d6f23a in surface_commit_pending (surface=surface@entry=0x556bcc119440) at ../types/wlr_surface.c:427
        invalid_buffer = true
        subsurface = 0x556bcc119688
#6  0x00007f86a8d6f820 in surface_commit (client=<optimized out>, resource=<optimized out>) at ../types/wlr_surface.c:499
        surface = 0x556bcc119440
        subsurface = <optimized out>
#7  0x00007f86a84bea8d in  () at /usr/lib/libffi.so.7
#8  0x00007f86a84be01b in  () at /usr/lib/libffi.so.7
#9  0x00007f86a8dc7f62 in  () at /usr/lib/libwayland-server.so.0
#10 0x00007f86a8dc42dc in  () at /usr/lib/libwayland-server.so.0
#11 0x00007f86a8dc5faa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#12 0x00007f86a8dc44e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#13 0x0000556bc9581981 in server_run (server=0x556bc95f62e0 <server>) at ../sway/server.c:234
#14 0x0000556bc9580eea in main (argc=1, argv=0x7fffacebef28) at ../sway/main.c:410
```

**Edit**: Debug symbols added.

**Comment by TheAvidDev** [comment]
Seems to have been some issue with which version of sway/wlroots was being used.

**Comment by emersion** [comment]
Yeah, always update and build Sway and wlroots together. Using something else than the latest commit of both will cause issues.

**Comment by TheAvidDev** [comment]
Yeah, I have both cloned but I've also installed them from the AUR so there was some weird conflict -- not really sure.
