### ISSUE TITLE
[X11 backend] glutin cannot create egl context

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#263]
[glutin](https://github.com/tomaka/glutin) cannot create an egl context on the X11 backend.

```
git clone https://github.com/tomaka/glutin
cd glutin
cargo run --example window
```

https://github.com/tomaka/glutin/blob/master/src/api/egl/mod.rs#L731

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/window`
[3599635.716]  -> wl_display@1.get_registry(new id wl_registry@2)
[3599635.741]  -> wl_display@1.sync(new id wl_callback@3)
[3599635.878] wl_display@1.delete_id(3)
[3599635.897] wl_registry@2.global(1, "wl_shm", 1)
[3599635.915] wl_registry@2.global(2, "wl_compositor", 4)
[3599635.923] wl_registry@2.global(3, "wl_subcompositor", 1)
[3599635.939]  -> wl_registry@2.bind(2, "wl_compositor", 4, new id [unknown]@4)
[3599635.947]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@5)
[3599635.955]  -> wl_registry@2.bind(3, "wl_subcompositor", 1, new id [unknown]@6)
[3599635.964] wl_registry@2.global(4, "zxdg_shell_v6", 1)
[3599635.970]  -> wl_registry@2.bind(4, "zxdg_shell_v6", 1, new id [unknown]@7)
[3599635.980] wl_registry@2.global(5, "wl_shell", 1)
[3599635.988] wl_registry@2.global(6, "gamma_control_manager", 1)
[3599635.993] wl_registry@2.global(7, "orbital_screenshooter", 1)
[3599635.999] wl_registry@2.global(8, "wl_seat", 6)
[3599636.004] wl_registry@2.global(9, "wl_data_device_manager", 3)
[3599636.010] wl_registry@2.global(10, "wl_output", 3)
[3599636.016]  -> wl_registry@2.bind(10, "wl_output", 1, new id [unknown]@8)
[3599636.026] wl_callback@3.done(175)
[3599636.030]  -> wl_display@1.sync(new id wl_callback@3)
[3599636.190] wl_display@1.delete_id(3)
[3599636.221] wl_output@8.geometry(0, 0, 0, 0, 0, "", "", 0)
[3599636.239] wl_output@8.mode(1, 1074, 611, 0)
[3599636.246] wl_callback@3.done(175)
[3599636.373]  -> wl_registry@2.bind(8, "wl_seat", 5, new id [unknown]@3)
[3599636.404]  -> wl_compositor@4.create_surface(new id wl_surface@9)
[3599636.412]  -> wl_registry@2.bind(8, "wl_seat", 5, new id [unknown]@10)
[3599636.576]  -> wl_shm@5.create_pool(new id wl_shm_pool@11, fd 5, 76800)
[3599636.589]  -> wl_compositor@4.create_surface(new id wl_surface@12)
[3599636.594]  -> wl_compositor@4.create_surface(new id wl_surface@13)
[3599636.597]  -> wl_compositor@4.create_surface(new id wl_surface@14)
[3599636.601]  -> wl_compositor@4.create_surface(new id wl_surface@15)
[3599636.608]  -> wl_subcompositor@6.get_subsurface(new id wl_subsurface@16, wl_surface@12, wl_surface@9)
[3599636.615]  -> wl_subcompositor@6.get_subsurface(new id wl_subsurface@17, wl_surface@13, wl_surface@9)
[3599636.622]  -> wl_subcompositor@6.get_subsurface(new id wl_subsurface@18, wl_surface@14, wl_surface@9)
[3599636.628]  -> wl_subcompositor@6.get_subsurface(new id wl_subsurface@19, wl_surface@15, wl_surface@9)
[3599636.635]  -> wl_subsurface@16.set_desync()
[3599636.638]  -> wl_subsurface@17.set_desync()
[3599636.640]  -> wl_subsurface@18.set_desync()
[3599636.642]  -> wl_subsurface@19.set_desync()
[3599636.644]  -> zxdg_shell_v6@7.get_xdg_surface(new id zxdg_surface_v6@20, wl_surface@9)
[3599636.650]  -> zxdg_surface_v6@20.get_toplevel(new id zxdg_toplevel_v6@21)
[3599636.654]  -> wl_surface@9.commit()
[3599636.657]  -> wl_seat@10.get_pointer(new id wl_pointer@22)
[3599636.783]  -> wl_shm@5.create_pool(new id wl_shm_pool@23, fd 7, 1024)
[3599636.943]  -> wl_shm_pool@23.resize(4352)
[3599636.966]  -> wl_shm_pool@23.resize(11008)
[3599637.011]  -> wl_shm_pool@23.resize(24320)
[3599637.092]  -> wl_shm_pool@23.resize(50944)
[3599637.630]  -> wl_shm_pool@23.resize(104192)
[3599637.656]  -> wl_shm_pool@23.resize(210688)
[3599637.938]  -> wl_shm_pool@23.resize(423680)
[3599639.173]  -> wl_shm_pool@23.resize(849664)
[3599640.660]  -> wl_shm_pool@23.resize(1701632)
[3599645.736]  -> wl_compositor@4.create_surface(new id wl_surface@24)
[3599645.747]  -> wl_shm_pool@11.resize(78336)
[3599672.248]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@25, 0, 816, 24, 3264, 0)
[3599672.262]  -> wl_surface@12.attach(wl_buffer@25, 0, 0)
[3599672.268]  -> wl_subsurface@16.set_position(-8, -24)
[3599672.273]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@26, 0, 8, 600, 32, 0)
[3599672.284]  -> wl_surface@13.attach(wl_buffer@26, 0, 0)
[3599672.289]  -> wl_subsurface@17.set_position(800, 0)
[3599672.293]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@27, 0, 816, 8, 3264, 0)
[3599672.308]  -> wl_surface@14.attach(wl_buffer@27, 0, 0)
[3599672.313]  -> wl_subsurface@18.set_position(-8, 600)
[3599672.317]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@28, 0, 8, 600, 32, 0)
[3599672.327]  -> wl_surface@15.attach(wl_buffer@28, 0, 0)
[3599672.332]  -> wl_subsurface@19.set_position(-8, 0)
[3599672.337]  -> wl_surface@12.commit()
[3599672.339]  -> wl_surface@13.commit()
[3599672.341]  -> wl_surface@14.commit()
[3599672.343]  -> wl_surface@15.commit()
[3599672.351]  -> wl_buffer@25.destroy()
[3599672.354]  -> wl_buffer@26.destroy()
[3599672.356]  -> wl_buffer@27.destroy()
[3599672.359]  -> wl_buffer@28.destroy()
[3599672.374]  -> wl_shm_pool@11.resize(99840)
[3599706.192]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@29, 0, 1040, 24, 4160, 0)
[3599706.205]  -> wl_surface@12.attach(wl_buffer@29, 0, 0)
[3599706.210]  -> wl_subsurface@16.set_position(-8, -24)
[3599706.215]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@30, 0, 8, 768, 32, 0)
[3599706.224]  -> wl_surface@13.attach(wl_buffer@30, 0, 0)
[3599706.230]  -> wl_subsurface@17.set_position(1024, 0)
[3599706.234]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@31, 0, 1040, 8, 4160, 0)
[3599706.243]  -> wl_surface@14.attach(wl_buffer@31, 0, 0)
[3599706.249]  -> wl_subsurface@18.set_position(-8, 768)
[3599706.253]  -> wl_shm_pool@11.create_buffer(new id wl_buffer@32, 0, 8, 768, 32, 0)
[3599706.263]  -> wl_surface@15.attach(wl_buffer@32, 0, 0)
[3599706.268]  -> wl_subsurface@19.set_position(-8, 0)
[3599706.272]  -> wl_surface@12.commit()
[3599706.274]  -> wl_surface@13.commit()
[3599706.276]  -> wl_surface@14.commit()
[3599706.278]  -> wl_surface@15.commit()
[3599706.280]  -> wl_display@1.sync(new id wl_callback@33)
[3599707.394] wl_display@1.delete_id(25)
[3599707.402] wl_display@1.delete_id(26)
[3599707.405] wl_display@1.delete_id(27)
[3599707.408] wl_display@1.delete_id(28)
[3599707.410] wl_display@1.delete_id(33)
[3599707.413] wl_seat@3.name("seat0")
[3599707.419] wl_seat@3.capabilities(7)
[3599707.423]  -> wl_seat@3.get_pointer(new id wl_pointer@28)
[3599707.429]  -> wl_seat@3.get_keyboard(new id wl_keyboard@27)
[3599707.434] wl_callback@33.done(175)
[3599707.437] zxdg_toplevel_v6@21.configure(0, 0, array)
[3599707.446] zxdg_surface_v6@20.configure(176)
[3599707.450]  -> zxdg_surface_v6@20.ack_configure(176)
[3599708.818]  -> wl_display@1.get_registry(new id wl_registry@33)
[3599708.827]  -> wl_display@1.sync(new id wl_callback@26)
[3599708.963] wl_display@1.delete_id(26)
[3599708.970] wl_registry@33.global(1, "wl_shm", 1)
[3599708.976] wl_registry@33.global(2, "wl_compositor", 4)
[3599708.981] wl_registry@33.global(3, "wl_subcompositor", 1)
[3599708.986] wl_registry@33.global(4, "zxdg_shell_v6", 1)
[3599708.991] wl_registry@33.global(5, "wl_shell", 1)
[3599708.996] wl_registry@33.global(6, "gamma_control_manager", 1)
[3599709.001] wl_registry@33.global(7, "orbital_screenshooter", 1)
[3599709.006] wl_registry@33.global(8, "wl_seat", 6)
[3599709.011] wl_registry@33.global(9, "wl_data_device_manager", 3)
[3599709.016] wl_registry@33.global(10, "wl_output", 3)
[3599709.021] wl_callback@26.done(177)
[3599709.025]  -> wl_display@1.get_registry(new id wl_registry@26)
[3599709.029]  -> wl_display@1.sync(new id wl_callback@25)
[3599709.124] wl_display@1.delete_id(25)
[3599709.128] wl_registry@26.global(1, "wl_shm", 1)
[3599709.133]  -> wl_registry@26.bind(1, "wl_shm", 1, new id [unknown]@34)
[3599709.140] wl_registry@26.global(2, "wl_compositor", 4)
[3599709.145] wl_registry@26.global(3, "wl_subcompositor", 1)
[3599709.150] wl_registry@26.global(4, "zxdg_shell_v6", 1)
[3599709.155] wl_registry@26.global(5, "wl_shell", 1)
[3599709.160] wl_registry@26.global(6, "gamma_control_manager", 1)
[3599709.165] wl_registry@26.global(7, "orbital_screenshooter", 1)
[3599709.170] wl_registry@26.global(8, "wl_seat", 6)
[3599709.175] wl_registry@26.global(9, "wl_data_device_manager", 3)
[3599709.180] wl_registry@26.global(10, "wl_output", 3)
[3599709.185] wl_callback@25.done(177)
[3599709.188]  -> wl_display@1.sync(new id wl_callback@25)
[3599709.233] wl_display@1.delete_id(25)
[3599709.239] wl_shm@34.format(0)
[3599709.242] wl_shm@34.format(1)
[3599709.244] wl_callback@25.done(177)
thread 'main' panicked at 'eglCreateContext failed: 0x3009', src/api/egl/mod.rs:731:17
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_new
   6: std::panicking::begin_panic_fmt
   7: glutin::api::egl::create_context
             at src/api/egl/mod.rs:731
   8: glutin::api::egl::ContextPrototype::finish_impl
             at src/api/egl/mod.rs:427
   9: glutin::api::egl::ContextPrototype::finish
             at src/api/egl/mod.rs:379
  10: glutin::platform::platform::wayland::Context::new::{{closure}}
             at src/platform/linux/wayland.rs:39
  11: <core::result::Result<T, E>>::and_then
             at /builddir/build/BUILD/rustc-1.20.0-src/src/libcore/result.rs:602
  12: glutin::platform::platform::wayland::Context::new
             at src/platform/linux/wayland.rs:38
  13: glutin::platform::platform::Context::new
             at src/platform/linux/mod.rs:47
  14: glutin::GlWindow::new
             at src/lib.rs:322
  15: window::main
             at examples/window.rs:11
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start
  18: main
  19: __libc_start_main
  20: _start
[3599728.314]  -> wl_surface@9.destroy()
[3599728.396]  -> wl_shm_pool@23.destroy()
```

**Comment by emersion** [comment]
Cannot reproduce
