### ISSUE TITLE
Segfault when closing file picker

### ISSUE THREAD

**Issue by ppascher** [swaywm/wlroots#2721]
I get a sway segfault in in libwlroots `xdg_imported_handle_resource_destroy` when closing a file picker dialogue opened by firefox.
Stack trace:
```Core was generated by sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd38a38cd5f in finish_imported (imported=0x557928453800) at ../types/wlr_xdg_foreign_v1.c:151
151		wl_list_for_each_safe(child, child_tmp, &imported->children, link) {
[Current thread is 1 (Thread 0x7fd38946e980 (LWP 19197))]
(gdb) bt full
#0  0x00007fd38a38cd5f in finish_imported (imported=0x557928453800) at ../types/wlr_xdg_foreign_v1.c:151
        child = 0xfffffffffffffff0
        child_tmp = 0x7ffde3763340
#1  0x00007fd38a38d1a3 in xdg_imported_handle_resource_destroy (resource=0x55792841df90) at ../types/wlr_xdg_foreign_v1.c:279
        imported = 0x557928453800
#2  0x00007fd38a3e7800 in  () at /usr/lib/libwayland-server.so.0
#3  0x00007fd38a3e7f71 in wl_resource_destroy () at /usr/lib/libwayland-server.so.0
#4  0x00007fd38a38c972 in xdg_imported_handle_destroy (client=0x557928454b80, resource=0x55792841df90) at ../types/wlr_xdg_foreign_v1.c:28
#5  0x00007fd389aa8acd in  () at /usr/lib/libffi.so.7
#6  0x00007fd389aa803a in  () at /usr/lib/libffi.so.7
#7  0x00007fd38a3ed124 in  () at /usr/lib/libwayland-server.so.0
#8  0x00007fd38a3e857c in  () at /usr/lib/libwayland-server.so.0
#9  0x00007fd38a3eb07a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#10 0x00007fd38a3e8be7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#11 0x0000557926147b7d in server_run (server=0x5579261bf580 <server>) at ../sway/server.c:260
#12 0x000055792614701d in main (argc=1, argv=0x7ffde37639a8) at ../sway/main.c:431
```
This is on latest sway and wlroots master.

**Comment by emersion** [comment]
cc @ammen99

**Comment by ppascher** [comment]
I just want to confirm #2731 fixes the issue for me. Thank you @tadeokondrak.
