### ISSUE TITLE
crash when returning from locked screen

### ISSUE THREAD

**Issue by emmanueltouzery** [swaywm/wlroots#2729]
I have regular crashes when returning from locked screen. It's probably unrelated, but I have in my configuration `swayidle`, not `swayidle -w`, otherwise the lock screen doesn't trigger.

Here's a stack from a crash:

Feb 07 11:07:41 localhost.localdomain systemd-coredump[23895]: Process 2092 (sway) of user 1000 dumped core.
               
               Stack trace of thread 2092:
               #0  0x00007f9a23678a74 st_texture_release_all_sampler_views (iris_dri.so + 0x144a74)
               #1  0x00007f9a2380307e _mesa_delete_texture_image (iris_dri.so + 0x2cf07e)
               #2  0x00007f9a23813959 _mesa_delete_texture_object (iris_dri.so + 0x2df959)
               #3  0x00007f9a23813c58 _mesa_reference_texobj_ (iris_dri.so + 0x2dfc58)
               #4  0x00007f9a238142e9 delete_textures.part.0 (iris_dri.so + 0x2e02e9)
               #5  0x00007f9a263275a3 n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x305a3)
               #6  0x00007f9a263244ba n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x2d4ba)
               #7  0x00007f9a2635b600 n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x64600)
               #8  0x00007f9a2635b28c n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x6428c)
               #9  0x00007f9a2635b38e n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x6438e)
               #10 0x0000000000465f31 n/a (/home/emmanuel/home/sway/build/sway/sway + 0x65f31)
               #11 0x0000000000426468 n/a (/home/emmanuel/home/sway/build/sway/sway + 0x26468)
               #12 0x0000000000426803 n/a (/home/emmanuel/home/sway/build/sway/sway + 0x26803)
               #13 0x0000000000426926 n/a (/home/emmanuel/home/sway/build/sway/sway + 0x26926)
               #14 0x0000000000426ffa n/a (/home/emmanuel/home/sway/build/sway/sway + 0x26ffa)
               #15 0x00000000004270fe n/a (/home/emmanuel/home/sway/build/sway/sway + 0x270fe)
               #16 0x000000000046b21b n/a (/home/emmanuel/home/sway/build/sway/sway + 0x6b21b)
               #17 0x00007f9a26384148 n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x8d148)
               #18 0x00007f9a2637b05f n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x8405f)
               #19 0x00007f9a2637b2c3 n/a (/home/emmanuel/home/sway/build/subprojects/wlroots/libwlroots.so.7 + 0x842c3)
               #20 0x00007f9a2532eb10 ffi_call_unix64 (libffi.so.6 + 0x6b10)
               #21 0x00007f9a2532e0a3 ffi_call (libffi.so.6 + 0x60a3)
               #22 0x00007f9a25ccafd5 wl_closure_invoke.constprop.0 (libwayland-server.so.0 + 0x8fd5)
               #23 0x00007f9a25cceecc wl_client_connection_data (libwayland-server.so.0 + 0xcecc)
               #24 0x00007f9a25ccdac2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xbac2)
               #25 0x00007f9a25cce1a5 wl_display_run (libwayland-server.so.0 + 0xc1a5)
               #26 0x000000000041cbf0 n/a (/home/emmanuel/home/sway/build/sway/sway + 0x1cbf0)
               #27 0x000000000041c167 n/a (/home/emmanuel/home/sway/build/sway/sway + 0x1c167)
               #28 0x00007f9a25a9e1e2 __libc_start_main (libc.so.6 + 0x281e2)
               #29 0x000000000040e51e n/a (/home/emmanuel/home/sway/build/sway/sway + 0xe51e)

I'm not using the very latest git, but fairly recent, january 28:

4d43f1dd996e61e38d89adf0ad1435dac32e38a5 for sway
50b9921642af61487e2d0f425695342bf7c4ad78 for wlrooks

I cannot reproduce this bug reliably. It happens from time to time.

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by emmanueltouzery** [comment]
thank you! It is manually built, from git. I used these instructions but didn't pass any special flags. I'm not sure which flags to pass.

I gather I should set this up: `ASAN_OPTIONS=abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1` ?

**Comment by emersion** [comment]
Hm. Then I'm not sure why you don't get debug symbols. Asan shouldn't be required.

Can you try `coredumpctl gdb` and then `bt full` in the GDB REPL?

**Comment by emmanueltouzery** [comment]
ok, I managed to get it. Thanks for the pointer to coredumpctl!

I did coredumpctl list, found a match for sway, pid 2092, `coredumpctl -o sway.dump dump 2092`, then `gdb /home/emmanuel/home/sway/build/sway/sway sway.dump`.

```
(gdb) bt full
#0  0x00007f9a23678a74 in st_texture_release_all_sampler_views () at /usr/lib64/dri/iris_dri.so
#1  0x00007f9a2380307e in _mesa_delete_texture_image () at /usr/lib64/dri/iris_dri.so
#2  0x00007f9a23813959 in _mesa_delete_texture_object () at /usr/lib64/dri/iris_dri.so
#3  0x00007f9a23813c58 in _mesa_reference_texobj_ () at /usr/lib64/dri/iris_dri.so
#4  0x00007f9a238142e9 in delete_textures.part () at /usr/lib64/dri/iris_dri.so
#5  0x00007f9a263275a3 in gles2_texture_destroy (wlr_texture=0x3119330) at ../subprojects/wlroots/render/gles2/texture.c:118
        texture = 0x3119330
        prev_ctx = {display = 0x0, context = 0x0, draw_surface = 0x0, read_surface = 0x0}
        __func__ = "gles2_texture_destroy"
#6  0x00007f9a263244ba in wlr_texture_destroy (texture=0x3119330) at ../subprojects/wlroots/render/wlr_texture.c:16
#7  0x00007f9a2635b600 in client_buffer_destroy (_buffer=0x31a5710) at ../subprojects/wlroots/types/wlr_buffer.c:121
        buffer = 0x31a5710
#8  0x00007f9a2635b28c in buffer_consider_destroy (buffer=0x31a5710) at ../subprojects/wlroots/types/wlr_buffer.c:26
#9  0x00007f9a2635b38e in wlr_buffer_unlock (buffer=0x31a5710) at ../subprojects/wlroots/types/wlr_buffer.c:56
        __PRETTY_FUNCTION__ = "wlr_buffer_unlock"
#10 0x0000000000465f31 in view_remove_saved_buffer (view=0x314ee90) at ../sway/tree/view.c:1337
        __PRETTY_FUNCTION__ = "view_remove_saved_buffer"
        saved_buf = 0x30b8be0
        tmp = 0x314eeb8
#11 0x0000000000426468 in apply_container_state (container=0x318daa0, state=0x31d7b80) at ../sway/desktop/transaction.c:237
        view = 0x314ee90
#12 0x0000000000426803 in transaction_apply (transaction=0x2f91640) at ../sway/desktop/transaction.c:309
        instruction = 0x31d7b70
        node = 0x318daa0
        i = 18
#13 0x0000000000426926 in transaction_progress_queue () at ../sway/desktop/transaction.c:348
        transaction = 0x2f91640
#14 0x0000000000426ffa in set_instruction_ready (instruction=0x3012110) at ../sway/desktop/transaction.c:510
        transaction = 0x2f91640
#15 0x00000000004270fe in transaction_notify_view_ready_by_geometry (view=0x3097440, x=640, y=0, width=640, height=1056) at ../sway/desktop/transaction.c:531
--Type <RET> for more, q to quit, c to continue without paging--
        instruction = 0x3012110
#16 0x000000000046b21b in handle_commit (listener=0x3097588, data=0x309e1d0) at ../sway/desktop/xwayland.c:404
        xwayland_view = 0x3097440
        view = 0x3097440
        xsurface = 0x30971d0
        state = 0x309e238
#17 0x00007f9a26384148 in wlr_signal_emit_safe (signal=0x309e500, data=0x309e1d0) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x3097588
        l = 0x3097588
        cursor = {link = {prev = 0x3097588, next = 0x7ffd930f6900}, notify = 0x7f9a263840a1 <handle_noop>}
        end = {link = {prev = 0x7ffd930f6920, next = 0x309e500}, notify = 0x7f9a263840a1 <handle_noop>}
#18 0x00007f9a2637b05f in surface_commit_pending (surface=0x309e1d0) at ../subprojects/wlroots/types/wlr_surface.c:430
        invalid_buffer = true
        subsurface = 0x309e418
#19 0x00007f9a2637b2c3 in surface_commit (client=0x2fc7c10, resource=0x2fcd960) at ../subprojects/wlroots/types/wlr_surface.c:499
        surface = 0x309e1d0
        subsurface = 0x0
#20 0x00007f9a2532eb10 in ffi_call_unix64 () at /lib64/libffi.so.6
#21 0x00007f9a2532e0a3 in ffi_call () at /lib64/libffi.so.6
#22 0x00007f9a25ccafd5 in wl_closure_invoke.constprop () at /lib64/libwayland-server.so.0
#23 0x00007f9a25cceecc in wl_client_connection_data () at /lib64/libwayland-server.so.0
#24 0x00007f9a25ccdac2 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#25 0x00007f9a25cce1a5 in wl_display_run () at /lib64/libwayland-server.so.0
#26 0x000000000041cbf0 in server_run (server=0x491320 <server>) at ../sway/server.c:247
#27 0x000000000041c167 in main (argc=1, argv=0x7ffd930f71e8) at ../sway/main.c:431
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
--Type <RET> for more, q to quit, c to continue without paging--
            {{name = 0x4734b0 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x4734b5 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x4734bc "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x4734c5 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x4734cb "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x4734d3 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x4734db "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x4734ea "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x4734fa "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x472e70 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
(gdb) 
```
