### ISSUE TITLE
Crash on Sway startup in kernel 5.11

### ISSUE THREAD

**Issue by hedgepigdaniel** [swaywm/wlroots#2764]
The same issue doesn't happen on older kernels.

This is on:
 * mesa 20.3.4
 * kernel 5.11.2
 * sway 1.5.1
 * wlroots 0.12.0

```
#0  0x0000000000000000 in  ()
#1  0x00007fe2972ec8e1 in dri2_create_image_common(__DRIscreen*, int, int, int, unsigned int, uint64_t const*, unsigned int, void*)
    (_screen=<optimized out>, width=2560, height=1440, format=4099, use=use@entry=1, modifiers=0x561fb7052be0, count=6, loaderPrivate=0x561fb71a62a0) at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:1056
#2  0x00007fe2972ec9b0 in dri2_create_image_with_modifiers(__DRIscreen*, int, int, int, uint64_t const*, unsigned int, void*)
    (dri_screen=<optimized out>, width=<optimized out>, height=<optimized out>, format=<optimized out>, modifiers=<optimized out>, count=<optimized out>, loaderPrivate=0x561fb71a62a0)
    at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:1097
#3  0x00007fe298f4d101 in gbm_dri_bo_create (gbm=0x561fb65d5a50, width=2560, height=1440, format=875713089, usage=0, modifiers=0x561fb7052be0, count=6) at ../mesa-20.3.4/src/gbm/backends/dri/gbm_dri.c:1172
#4  0x00007fe298f507f3 in gbm_bo_create_with_modifiers (gbm=<optimized out>, width=<optimized out>, height=<optimized out>, format=<optimized out>, modifiers=<optimized out>, count=<optimized out>)
    at ../mesa-20.3.4/src/gbm/main/gbm.c:494
#5  0x00007fe275fda454 in get_back_bo (dri2_surf=dri2_surf@entry=0x561fb71c0da0) at ../mesa-20.3.4/src/egl/drivers/dri2/platform_drm.c:248
#6  0x00007fe275fda67f in dri2_drm_image_get_buffers (driDrawable=<optimized out>, format=<optimized out>, stamp=<optimized out>, loaderPrivate=0x561fb71c0da0, buffer_mask=<optimized out>, buffers=0x7fffbc507bf0)
    at ../mesa-20.3.4/src/egl/drivers/dri2/platform_drm.c:403
#7  0x00007fe298f4a1fc in image_get_buffers (driDrawable=<optimized out>, format=<optimized out>, stamp=<optimized out>, loaderPrivate=<optimized out>, buffer_mask=<optimized out>, buffers=<optimized out>)
    at ../mesa-20.3.4/src/gbm/backends/dri/gbm_dri.c:139
#8  0x00007fe2972e7c0f in dri_image_drawable_get_buffers(dri_drawable*, __DRIimageList*, st_attachment_type const*, unsigned int)
    (drawable=drawable@entry=0x561fb71c10d0, images=images@entry=0x7fffbc507bf0, statts=statts@entry=0x561fb71c1798, statts_count=statts_count@entry=1) at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:282
#9  0x00007fe2972ece74 in dri2_allocate_textures(dri_context*, dri_drawable*, st_attachment_type const*, unsigned int) (ctx=0x561fb66b3450, drawable=0x561fb71c10d0, statts=0x561fb71c1798, statts_count=1)
    at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:415
#10 0x00007fe2972eb0b8 in dri_st_framebuffer_validate(st_context_iface*, st_framebuffer_iface*, st_attachment_type const*, unsigned int, pipe_resource**)
    (stctx=<optimized out>, stfbi=<optimized out>, statts=0x561fb71c1798, count=1, out=0x7fffbc507d60) at ../mesa-20.3.4/src/gallium/frontends/dri/dri_drawable.c:82
#11 0x00007fe2972f8df9 in st_framebuffer_validate(st_framebuffer*, st_context*) (stfb=0x561fb71c12c0, st=st@entry=0x561fb6726c00) at ../mesa-20.3.4/src/mesa/state_tracker/st_manager.c:223
#12 0x00007fe2972f9494 in st_api_make_current(st_api*, st_context_iface*, st_framebuffer_iface*, st_framebuffer_iface*) (stapi=<optimized out>, stctxi=0x561fb6726c00, stdrawi=0x561fb71c10d0, streadi=0x561fb71c10d0)
    at ../mesa-20.3.4/src/mesa/state_tracker/st_manager.c:1078
#13 0x00007fe2972eeb9a in dri_make_current(__DRIcontext*, __DRIdrawable*, __DRIdrawable*) (cPriv=<optimized out>, driDrawPriv=<optimized out>, driReadPriv=<optimized out>) at ../mesa-20.3.4/src/gallium/frontends/dri/dri_context.c:303
#14 0x00007fe2977da812 in driBindContext(__DRIcontext*, __DRIdrawable*, __DRIdrawable*) (pcp=0x561fb66b29d0, pdp=0x561fb70632c0, prp=0x561fb70632c0) at ../mesa-20.3.4/src/mesa/drivers/dri/common/dri_util.c:586
#15 0x00007fe275fdd053 in dri2_make_current (disp=0x561fb66ad2f0, dsurf=0x561fb71c0da0, rsurf=0x561fb71c0da0, ctx=<optimized out>) at ../mesa-20.3.4/src/egl/drivers/dri2/egl_dri2.c:1810
#16 0x00007fe275fcf774 in eglMakeCurrent (dpy=<optimized out>, draw=0x561fb71c0da0, read=0x561fb71c0da0, ctx=0x561fb65c5b80) at ../mesa-20.3.4/src/egl/main/eglapi.c:903
#17 0x00007fe298f730c7 in InternalMakeCurrentVendor
    (dpy=dpy@entry=0x561fb66a1db0, draw=draw@entry=0x561fb71c0da0, read=read@entry=0x561fb71c0da0, context=context@entry=0x561fb65c5b80, apiState=apiState@entry=0x561fb71a6aa0, vendor=vendor@entry=0x561fb66a9180)
    at ../libglvnd-v1.3.2/src/EGL/libegl.c:591
#18 0x00007fe298f732be in InternalMakeCurrentDispatch (dpy=dpy@entry=0x561fb66a1db0, draw=draw@entry=0x561fb71c0da0, read=read@entry=0x561fb71c0da0, context=context@entry=0x561fb65c5b80, vendor=vendor@entry=0x561fb66a9180)
    at ../libglvnd-v1.3.2/src/EGL/libegl.c:636
#19 0x00007fe298f745bb in eglMakeCurrent (dpy=<optimized out>, draw=draw@entry=0x561fb71c0da0, read=read@entry=0x561fb71c0da0, context=0x561fb65c5b80) at ../libglvnd-v1.3.2/src/EGL/libegl.c:746
#20 0x00007fe2998d715e in wlr_egl_make_current (egl=0x561fb65d7d18, surface=0x561fb71c0da0, buffer_age=buffer_age@entry=0x0) at ../wlroots-0.12.0/render/egl.c:430
#21 0x00007fe2998d729b in drm_surface_make_current (surf=surf@entry=0x561fb65d8468, buffer_age=buffer_age@entry=0x0) at ../wlroots-0.12.0/backend/drm/renderer.c:130
#22 0x00007fe2998d72e7 in drm_surface_render_black_frame (surf=surf@entry=0x561fb65d8468) at ../wlroots-0.12.0/backend/drm/renderer.c:366
#23 0x00007fe2998de59b in drm_connector_pageflip_renderer (conn=conn@entry=0x561fb71bdff0) at ../wlroots-0.12.0/backend/drm/drm.c:674
#24 0x00007fe2998de824 in drm_connector_init_renderer (conn=conn@entry=0x561fb71bdff0, mode=mode@entry=0x561fb714d210) at ../wlroots-0.12.0/backend/drm/drm.c:721
#25 0x00007fe2998deece in drm_connector_set_mode (conn=conn@entry=0x561fb71bdff0, wlr_mode=0x561fb714d210) at ../wlroots-0.12.0/backend/drm/drm.c:816
#26 0x00007fe2998e0429 in drm_connector_commit (output=0x561fb71bdff0) at ../wlroots-0.12.0/backend/drm/drm.c:574
#27 0x00007fe299909462 in wlr_output_commit (output=output@entry=0x561fb71bdff0) at ../wlroots-0.12.0/types/wlr_output.c:590
#28 0x0000561fb4c8267c in apply_output_config (oc=0x561fb71c0d30, output=0x561fb71c09f0) at ../sway-1.5.1/sway/config/output.c:410
#29 0x0000561fb4c71ab4 in handle_new_output (listener=0x561fb4cc5ee0 <server+96>, data=<optimized out>) at ../sway-1.5.1/sway/desktop/output.c:943
#30 0x00007fe29991ac03 in wlr_signal_emit_safe (signal=<optimized out>, data=0x561fb71bdff0) at ../wlroots-0.12.0/util/signal.c:29
#31 0x00007fe2998e0a3c in new_output_reemit (listener=<optimized out>, data=<optimized out>) at ../wlroots-0.12.0/backend/multi/backend.c:146
#32 0x00007fe29991ac03 in wlr_signal_emit_safe (signal=<optimized out>, data=0x561fb71bdff0) at ../wlroots-0.12.0/util/signal.c:29
#33 0x00007fe2998dfcbf in scan_drm_connectors (drm=0x561fb65d7c20) at ../wlroots-0.12.0/backend/drm/drm.c:1465
#34 0x00007fe2998dfcf3 in backend_start (backend=<optimized out>) at ../wlroots-0.12.0/backend/drm/backend.c:26
#35 0x00007fe2998d6bd5 in wlr_backend_start (backend=<optimized out>) at ../wlroots-0.12.0/backend/backend.c:36
#36 0x00007fe2998ea976 in multi_backend_start (wlr_backend=<optimized out>) at ../wlroots-0.12.0/backend/multi/backend.c:31
#37 0x00007fe2998d6bd5 in wlr_backend_start (backend=<optimized out>) at ../wlroots-0.12.0/backend/backend.c:36
#38 0x0000561fb4c69348 in server_start (server=0x561fb4cc5e80 <server>) at ../sway-1.5.1/sway/server.c:223
#39 0x0000561fb4c717fc in main (argc=1, argv=0x7fffbc5085f8) at ../sway-1.5.1/sway/main.c:395
(gdb) bt full
#0  0x0000000000000000 in  ()
#1  0x00007fe2972ec8e1 in dri2_create_image_common(__DRIscreen*, int, int, int, unsigned int, uint64_t const*, unsigned int, void*)
    (_screen=<optimized out>, width=2560, height=1440, format=4099, use=use@entry=1, modifiers=0x561fb7052be0, count=6, loaderPrivate=0x561fb71a62a0) at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:1056
        map = 0x7fe298197720 <dri2_format_table+480>
        screen = 0x561fb6635870
        pscreen = <optimized out>
        img = 0x561fb71a6080
        templ = 
          {reference = {count = 0}, width0 = 2560, height0 = 1440, depth0 = 1, array_size = 1, format = PIPE_FORMAT_B8G8R8A8_UNORM, target = PIPE_TEXTURE_2D, last_level = 0, nr_samples = 0, nr_storage_samples = 0, usage = 0, bind = 1048586, flags = 0, next = 0x0, screen = 0x0}
        tex_usage = 1048586
#2  0x00007fe2972ec9b0 in dri2_create_image_with_modifiers(__DRIscreen*, int, int, int, uint64_t const*, unsigned int, void*)
    (dri_screen=<optimized out>, width=<optimized out>, height=<optimized out>, format=<optimized out>, modifiers=<optimized out>, count=<optimized out>, loaderPrivate=0x561fb71a62a0)
    at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:1097
#3  0x00007fe298f4d101 in gbm_dri_bo_create (gbm=0x561fb65d5a50, width=2560, height=1440, format=875713089, usage=0, modifiers=0x561fb7052be0, count=6) at ../mesa-20.3.4/src/gbm/backends/dri/gbm_dri.c:1172
        dri = 0x561fb65d5a50
        bo = 0x561fb71a62a0
        dri_format = <optimized out>
        dri_use = <optimized out>
#4  0x00007fe298f507f3 in gbm_bo_create_with_modifiers (gbm=<optimized out>, width=<optimized out>, height=<optimized out>, format=<optimized out>, modifiers=<optimized out>, count=<optimized out>)
    at ../mesa-20.3.4/src/gbm/main/gbm.c:494
#5  0x00007fe275fda454 in get_back_bo (dri2_surf=dri2_surf@entry=0x561fb71c0da0) at ../mesa-20.3.4/src/egl/drivers/dri2/platform_drm.c:248
        dri2_dpy = <optimized out>
        surf = <optimized out>
        age = <optimized out>
#6  0x00007fe275fda67f in dri2_drm_image_get_buffers (driDrawable=<optimized out>, format=<optimized out>, stamp=<optimized out>, loaderPrivate=0x561fb71c0da0, buffer_mask=<optimized out>, buffers=0x7fffbc507bf0)
    at ../mesa-20.3.4/src/egl/drivers/dri2/platform_drm.c:403
        dri2_surf = 0x561fb71c0da0
        bo = <optimized out>
#7  0x00007fe298f4a1fc in image_get_buffers (driDrawable=<optimized out>, format=<optimized out>, stamp=<optimized out>, loaderPrivate=<optimized out>, buffer_mask=<optimized out>, buffers=<optimized out>)
    at ../mesa-20.3.4/src/gbm/backends/dri/gbm_dri.c:139
        surf = <optimized out>
        dri = <optimized out>
#8  0x00007fe2972e7c0f in dri_image_drawable_get_buffers(dri_drawable*, __DRIimageList*, st_attachment_type const*, unsigned int)
    (drawable=drawable@entry=0x561fb71c10d0, images=images@entry=0x7fffbc507bf0, statts=statts@entry=0x561fb71c1798, statts_count=statts_count@entry=1) at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:282
        dPriv = 0x561fb70632c0
        sPriv = 0x561fb66338b0
        image_format = 4099
        pf = PIPE_FORMAT_B8G8R8A8_UNORM
        buffer_mask = 1
        i = 1
        bind = 10
#9  0x00007fe2972ece74 in dri2_allocate_textures(dri_context*, dri_drawable*, st_attachment_type const*, unsigned int) (ctx=0x561fb66b3450, drawable=0x561fb71c10d0, statts=0x561fb71c1798, statts_count=1)
    at ../mesa-20.3.4/src/gallium/frontends/dri/dri2.c:415
        sPriv = <optimized out>
        dri_drawable = 0x561fb70632c0
        screen = 0x561fb6635870
        templ = 
          {reference = {count = 1}, width0 = 0, height0 = 29499, depth0 = 38725, array_size = 32738, format = PIPE_FORMAT_NONE, target = PIPE_TEXTURE_1D, last_level = 0, nr_samples = 0, nr_storage_samples = 0, usage = 0, bind = 3072070336, flags = 22047, next = 0x1, screen = 0x7fe2972f1907 <st_framebuffer_add_renderbuffer(st_framebuffer*, gl_buffer_index, _Bool)+261>}
        alloc_depthstencil = 0 '\000'
        i = <optimized out>
        j = <optimized out>
        bind = 32738
        image = 0x7fe298f55760 <image_loader_extension>
        images = {image_mask = 3072135296, back = 0x561fb66b29d0, front = 0x0}
        buffers = 0x0
        whandle = {type = 0, layer = 0, plane = 1, handle = 0, stride = 2537428267, offset = 32738, format = 140611175809208, modifier = 140611176765226}
        num_buffers = 1
#10 0x00007fe2972eb0b8 in dri_st_framebuffer_validate(st_context_iface*, st_framebuffer_iface*, st_attachment_type const*, unsigned int, pipe_resource**)
    (stctx=<optimized out>, stfbi=<optimized out>, statts=0x561fb71c1798, count=1, out=0x7fffbc507d60) at ../mesa-20.3.4/src/gallium/frontends/dri/dri_drawable.c:82
        ctx = 0x561fb66b3450
        drawable = 0x561fb71c10d0
        screen = 0x561fb6635870
        statt_mask = 2
        new_mask = 2
        new_stamp = <optimized out>
        i = <optimized out>
        lastStamp = 0
        textures = 0x561fb71c1200
        pscreen = <optimized out>
#11 0x00007fe2972f8df9 in st_framebuffer_validate(st_framebuffer*, st_context*) (stfb=0x561fb71c12c0, st=st@entry=0x561fb6726c00) at ../mesa-20.3.4/src/mesa/state_tracker/st_manager.c:223
        textures = 
          {0x0, 0x0, 0x561fb66b29d0, 0x7fe2972f91d3 <st_framebuffer_reference(st_framebuffer**, st_framebuffer*)+14>, 0x0, 0x7fe2972f93e5 <st_framebuffer_reuse_or_create(st_context*, gl_framebuffer*, st_framebuffer_iface*)+289>, 0x1f}
        width = <optimized out>
        height = <optimized out>
        i = <optimized out>
        changed = false
        new_stamp = 1
#12 0x00007fe2972f9494 in st_api_make_current(st_api*, st_context_iface*, st_framebuffer_iface*, st_framebuffer_iface*) (stapi=<optimized out>, stctxi=0x561fb6726c00, stdrawi=0x561fb71c10d0, streadi=0x561fb71c10d0)
    at ../mesa-20.3.4/src/mesa/state_tracker/st_manager.c:1078
        st = 0x561fb6726c00
        stdraw = 0x561fb71c12c0
        stread = 0x561fb71c12c0
        ret = <optimized out>
#13 0x00007fe2972eeb9a in dri_make_current(__DRIcontext*, __DRIdrawable*, __DRIdrawable*) (cPriv=<optimized out>, driDrawPriv=<optimized out>, driReadPriv=<optimized out>) at ../mesa-20.3.4/src/gallium/frontends/dri/dri_context.c:303
        ctx = 0x561fb66b3450
        draw = 0x561fb71c10d0
        read = <optimized out>
#14 0x00007fe2977da812 in driBindContext(__DRIcontext*, __DRIdrawable*, __DRIdrawable*) (pcp=0x561fb66b29d0, pdp=0x561fb70632c0, prp=0x561fb70632c0) at ../mesa-20.3.4/src/mesa/drivers/dri/common/dri_util.c:586
#15 0x00007fe275fdd053 in dri2_make_current (disp=0x561fb66ad2f0, dsurf=0x561fb71c0da0, rsurf=0x561fb71c0da0, ctx=<optimized out>) at ../mesa-20.3.4/src/egl/drivers/dri2/egl_dri2.c:1810
        dri2_dpy = 0x561fb66ad920
        dri2_ctx = <optimized out>
        old_disp = 0x0
        old_dri2_dpy = 0x0
        old_ctx = 0x0
        old_dsurf = 0x0
        old_rsurf = 0x0
        tmp_dsurf = 0x561fb70632c0
        tmp_rsurf = 0x7fe2972f0332 <dri2_create_buffer(__DRIscreen*, __DRIdrawable*, gl_config const*, boolean)+17>
        ddraw = 0x561fb70632c0
        rdraw = <optimized out>
        cctx = 0x561fb66b29d0
        egl_error = 12288
#16 0x00007fe275fcf774 in eglMakeCurrent (dpy=<optimized out>, draw=0x561fb71c0da0, read=0x561fb71c0da0, ctx=0x561fb65c5b80) at ../mesa-20.3.4/src/egl/main/eglapi.c:903
        disp = 0x561fb66ad2f0
        context = 0x561fb65c5b80
        draw_surf = 0x561fb71c0da0
        read_surf = 0x561fb71c0da0
        ret = <optimized out>
        __func__ = "eglMakeCurrent"
#17 0x00007fe298f730c7 in InternalMakeCurrentVendor
    (dpy=dpy@entry=0x561fb66a1db0, draw=draw@entry=0x561fb71c0da0, read=read@entry=0x561fb71c0da0, context=context@entry=0x561fb65c5b80, apiState=apiState@entry=0x561fb71a6aa0, vendor=vendor@entry=0x561fb66a9180)
    at ../libglvnd-v1.3.2/src/EGL/libegl.c:591
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "InternalMakeCurrentVendor"
#18 0x00007fe298f732be in InternalMakeCurrentDispatch (dpy=dpy@entry=0x561fb66a1db0, draw=draw@entry=0x561fb71c0da0, read=read@entry=0x561fb71c0da0, context=context@entry=0x561fb65c5b80, vendor=vendor@entry=0x561fb66a9180)
    at ../libglvnd-v1.3.2/src/EGL/libegl.c:636
        apiState = 0x561fb71a6aa0
        ret = 1
        __PRETTY_FUNCTION__ = "InternalMakeCurrentDispatch"
#19 0x00007fe298f745bb in eglMakeCurrent (dpy=<optimized out>, draw=draw@entry=0x561fb71c0da0, read=read@entry=0x561fb71c0da0, context=0x561fb65c5b80) at ../libglvnd-v1.3.2/src/EGL/libegl.c:746
        glas = <optimized out>
        apiState = <optimized out>
        oldVendor = <optimized out>
        newVendor = 0x561fb66a9180
        oldDpy = <optimized out>
        newDpy = 0x561fb66a1db0
        oldDraw = <optimized out>
        oldRead = <optimized out>
        oldContext = <optimized out>
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "eglMakeCurrent"
#20 0x00007fe2998d715e in wlr_egl_make_current (egl=0x561fb65d7d18, surface=0x561fb71c0da0, buffer_age=buffer_age@entry=0x0) at ../wlroots-0.12.0/render/egl.c:430
#21 0x00007fe2998d729b in drm_surface_make_current (surf=surf@entry=0x561fb65d8468, buffer_age=buffer_age@entry=0x0) at ../wlroots-0.12.0/backend/drm/renderer.c:130
#22 0x00007fe2998d72e7 in drm_surface_render_black_frame (surf=surf@entry=0x561fb65d8468) at ../wlroots-0.12.0/backend/drm/renderer.c:366
        renderer = <optimized out>
#23 0x00007fe2998de59b in drm_connector_pageflip_renderer (conn=conn@entry=0x561fb71bdff0) at ../wlroots-0.12.0/backend/drm/drm.c:674
        crtc = <optimized out>
        plane = 0x561fb65d8460
#24 0x00007fe2998de824 in drm_connector_init_renderer (conn=conn@entry=0x561fb71bdff0, mode=mode@entry=0x561fb714d210) at ../wlroots-0.12.0/backend/drm/drm.c:721
        drm = 0x561fb65d7c20
        crtc = 0x561fb65c3bc0
        plane = 0x561fb65d8460
        width = 2560
        height = 1440
        format = 875713089
        modifiers = true
        no_modifiers = <optimized out>
#25 0x00007fe2998deece in drm_connector_set_mode (conn=conn@entry=0x561fb71bdff0, wlr_mode=0x561fb714d210) at ../wlroots-0.12.0/backend/drm/drm.c:816
        drm = 0x561fb65d7c20
        mode = 0x561fb714d210
#26 0x00007fe2998e0429 in drm_connector_commit (output=0x561fb71bdff0) at ../wlroots-0.12.0/backend/drm/drm.c:574
        wlr_mode = <optimized out>
        enable = <optimized out>
        conn = 0x561fb71bdff0
        drm = 0x561fb65d7c20
        __PRETTY_FUNCTION__ = "drm_connector_commit"
#27 0x00007fe299909462 in wlr_output_commit (output=output@entry=0x561fb71bdff0) at ../wlroots-0.12.0/types/wlr_output.c:590
        now = {tv_sec = 1583, tv_nsec = 667746172}
        pre_event = {output = 0x561fb71bdff0, when = 0x7fffbc508160}
        event = {output = 0x0, committed = 0, when = 0x561fb65d7c20}
        scale_updated = <optimized out>
        geometry_updated = <optimized out>
#28 0x0000561fb4c8267c in apply_output_config (oc=0x561fb71c0d30, output=0x561fb71c09f0) at ../sway-1.5.1/sway/config/output.c:410
        wlr_output = 0x561fb71bdff0
        output_box = <optimized out>
#29 0x0000561fb4c71ab4 in handle_new_output (listener=0x561fb4cc5ee0 <server+96>, data=<optimized out>) at ../sway-1.5.1/sway/desktop/output.c:943
        server = 0x561fb4cc5e80 <server>
        wlr_output = <optimized out>
        output = 0x561fb71c09f0
        oc = 0x561fb71c0d30
#30 0x00007fe29991ac03 in wlr_signal_emit_safe (signal=<optimized out>, data=0x561fb71bdff0) at ../wlroots-0.12.0/util/signal.c:29
        pos = 0x561fb4cc5ee0 <server+96>
        l = 0x561fb4cc5ee0 <server+96>
        cursor = {link = {prev = 0x561fb4cc5ee0 <server+96>, next = 0x7fffbc508220}, notify = 0x7fe29991382c <handle_noop>}
        end = {link = {prev = 0x7fffbc508240, next = 0x561fb65bd3e8}, notify = 0x7fe29991382c <handle_noop>}
#31 0x00007fe2998e0a3c in new_output_reemit (listener=<optimized out>, data=<optimized out>) at ../wlroots-0.12.0/backend/multi/backend.c:146
        state = <optimized out>
#32 0x00007fe29991ac03 in wlr_signal_emit_safe (signal=<optimized out>, data=0x561fb71bdff0) at ../wlroots-0.12.0/util/signal.c:29
        pos = 0x561fb6caa5f8
        l = 0x561fb6caa5f8
        cursor = {link = {prev = 0x561fb6caa5f8, next = 0x7fffbc508290}, notify = 0x7fe29991382c <handle_noop>}
        end = {link = {prev = 0x7fffbc5082b0, next = 0x561fb65d7c48}, notify = 0x7fe29991382c <handle_noop>}
#33 0x00007fe2998dfcbf in scan_drm_connectors (drm=0x561fb65d7c20) at ../wlroots-0.12.0/backend/drm/drm.c:1465
        i = 0
        res = 0x561fb71a6aa0
        seen_len = 0
        seen = 0x7fffbc508320
        new_outputs_len = 1
        new_outputs = 0x7fffbc5082f0
        conn = <optimized out>
        tmp_conn = <optimized out>
        index = <optimized out>
#34 0x00007fe2998dfcf3 in backend_start (backend=<optimized out>) at ../wlroots-0.12.0/backend/drm/backend.c:26
        drm = <optimized out>
#35 0x00007fe2998d6bd5 in wlr_backend_start (backend=<optimized out>) at ../wlroots-0.12.0/backend/backend.c:36
#36 0x00007fe2998ea976 in multi_backend_start (wlr_backend=<optimized out>) at ../wlroots-0.12.0/backend/multi/backend.c:31
        backend = 0x561fb65bd3c0
        sub = 0x561fb6caa5d0
#37 0x00007fe2998d6bd5 in wlr_backend_start (backend=<optimized out>) at ../wlroots-0.12.0/backend/backend.c:36
#38 0x0000561fb4c69348 in server_start (server=0x561fb4cc5e80 <server>) at ../sway-1.5.1/sway/server.c:223
#39 0x0000561fb4c717fc in main (argc=1, argv=0x7fffbc5085f8) at ../sway-1.5.1/sway/main.c:395
        config_path = 0x0
        usage = 0x561fb4ca82b0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = 
            {{name = 0x561fb4ca7665 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x561fb4caa627 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x561fb4ca766a "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x561fb4ca7673 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x561fb4ca7313 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x561fb4ca54a0 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x561fb4ca7679 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x561fb4ca7688 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x561fb4ca7698 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
```

**Comment by hedgepigdaniel** [comment]
This seems to have been solved, I think my a newer version of mesa.
