### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by g3r** [swaywm/wlroots#2807]
Since commit e0258f4 sway crashes with:
```
err: main.c:400: shm: XRGB image format not available
zsh: segmentation fault (core dumped)  sway
```

**Comment by kennylevinsen** [comment]
Please share a stack trace and debug output.

**Comment by g3r** [comment]
[sway.log](https://github.com/swaywm/wlroots/files/6208799/sway.log)

Backtrace adding "handle SIG33 noprint nostop"
```
(gdb) bt full
#0  0x00007ffff7972b70 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x000055555556f8f2 in  ()
#2  0x00007ffff79206ae in wlr_signal_emit_safe
    (signal=<optimized out>, data=0x5555562f35e0) at ../wlroots-git/util/signal.c:29
        pos = 0x5555555da118
        l = 0x5555555da118
        cursor = 
          {link = {prev = 0x5555555da118, next = 0x7fffffffdad0}, notify = 0x7ffff791a790 <handle_noop>}
        end = 
          {link = {prev = 0x7fffffffdaf0, next = 0x555555eb7500}, notify = 0x7ffff791a790 <handle_noop>}
#3  0x00007ffff7070acd in  () at /usr/lib/libffi.so.7
#4  0x00007ffff707003a in  () at /usr/lib/libffi.so.7
#5  0x00007ffff7972124 in  () at /usr/lib/libwayland-server.so.0
#6  0x00007ffff796d57c in  () at /usr/lib/libwayland-server.so.0
#7  0x00007ffff797007a in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#8  0x00007ffff796dbe7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#9  0x00005555555648cb in  ()
#10 0x00007ffff7687b25 in __libc_start_main () at /usr/lib/libc.so.6
#11 0x0000555555564c6e in  ()
```

**Comment by emersion** [comment]
It doesn't seem like this stack trace is complete.

**Comment by emersion** [comment]
Are you sure you're using the latest Sway commit?

**Comment by g3r** [comment]
sway https://github.com/swaywm/sway/commit/1d62d6bfa09860d7a59640dcb20d5273a55401c4
wlroots https://github.com/swaywm/wlroots/commit/80dbb9ba71bd7d035523010db9bce149c8dd7e02

The backtrace was made running "gdb sway" from inside plasma wayland. If I run it from the console the system hangs completely after "(gdb) r". I needed to add "handle SIG33 noprint nostop" because otherwise it never reaches the crash state. The only thing I see is a grey background and a frozen cursor.

**Comment by g3r** [comment]
Maybe better backtrace:
```
(gdb) thread apply all bt

Thread 13 (Thread 0x7fffc6ffd640 (LWP 4412) "sway:disk$3"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7fffc77fe640 (LWP 4411) "sway:disk$2"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fffc7fff640 (LWP 4410) "sway:disk$1"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.--Type <RET> for more, q to quit, c to continue without paging--
0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7fffdcff9640 (LWP 4409) "sway:disk$0"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fffdd7fa640 (LWP 4400) "sway:disk$3"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7fffddffb640 (LWP 4399) "sway:disk$2"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffde7fc640 (LWP 4398) "sway:disk$1"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffdeffd640 (LWP 4397) "sway:disk$0"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffdf7fe640 (LWP 4396) "sway:disk$3"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffdffff640 (LWP 4395) "sway:disk$2"):
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffecca2640 (LWP 4394) "sway:disk$1"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffed4a3640 (LWP 4393) "sway:disk$0"):
#0  0x00007ffff76539ba in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007ffff764d260 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.--Type <RET> for more, q to quit, c to continue without paging--
0
#2  0x00007ffff5722cec in  () at /usr/lib/dri/iris_dri.so
#3  0x00007ffff57214c8 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007ffff7647299 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7760053 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff6a3e980 (LWP 4388) "sway"):
#0  0x00007ffff7972b70 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x000055555556f8f2 in  ()
#2  0x00007ffff792164e in  () at /usr/lib/libwlroots.so.7
#3  0x00007ffff7071acd in  () at /usr/lib/libffi.so.7
#4  0x00007ffff707103a in  () at /usr/lib/libffi.so.7
#5  0x00007ffff7972124 in  () at /usr/lib/libwayland-server.so.0
#6  0x00007ffff796d57c in  () at /usr/lib/libwayland-server.so.0
#7  0x00007ffff797007a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#8  0x00007ffff796dbe7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#9  0x00005555555648cb in  ()
#10 0x00007ffff7688b25 in __libc_start_main () at /usr/lib/libc.so.6
#11 0x0000555555564c6e in  ()
```

**Comment by emersion** [comment]
Still missing symbols and line numbers.

**Comment by emersion** [comment]
Confirmed on IRC that this is due to an old Sway copy.

You must always rebuild sway when wlroots is upgraded.

**Comment by g3r** [comment]
Confirmed:
The crash only happens with the archlinux aur packages sway-git wlroots-git.
Compiling sway and wlroots works fine:
https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subprojectsway
Deleting the aur helper cache and reinstalling sway fixes the problem. Thanks for the help.
