### ISSUE TITLE
handle_tablet_tool_proximity: Assertion `tool->pad_refs == 1' failed.

### ISSUE THREAD

**Issue by FreeFull** [swaywm/wlroots#3110]
- **Sway Version:**
  - sway version 1.6-c9060bcc (Aug 14 2021, branch 'master')

- **Debug Log:**
  - https://gist.github.com/FreeFull/ad9f78c2541ab3299d770f89a24adb41

- **Configuration File:**
  - Default configuration

- **Stack Trace:**
```
(gdb) bt full
#0  0x00007fe148a41d22 in raise () at /usr/lib/libc.so.6
swaywm/sway#1  0x00007fe148a2b862 in abort () at /usr/lib/libc.so.6
swaywm/sway#2  0x00007fe148a2b747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
swaywm/sway#3  0x00007fe148a3a616 in  () at /usr/lib/libc.so.6
swaywm/sway#4  0x00007fe148c8df9e in handle_tablet_tool_proximity (libinput_dev=0x55b0917203b0, event=0x55b091b0bcc0) at ../wlroots-git/backend/libinput/tablet_tool.c:283
        tablet = <optimized out>
        i = <optimized out>
        iter = <optimized out>
        wlr_dev = 0x55b0918c31a0
        tevent = 0x55b091b0bcc0
        wlr_event = {device = 0x55b0918c31a0, tool = 0x55b091a3b5b0, time_msec = 17468483, x = 0.55645571964260909, y = 0.57084660395526254, state = WLR_TABLET_TOOL_PROXIMITY_OUT}
        tool = 0x55b091a3b5b0
        libinput_dev = 0x55b0917203b0
        event_type = <optimized out>
        event = 0x55b091b0bcc0
        backend = <optimized out>
        ret = <optimized out>
swaywm/sway#5  handle_libinput_event (event=0x55b091b0bcc0, backend=0x55b090be1e30) at ../wlroots-git/backend/libinput/events.c:281
        libinput_dev = 0x55b0917203b0
        event_type = <optimized out>
        event = 0x55b091b0bcc0
        backend = <optimized out>
        ret = <optimized out>
swaywm/sway#6  handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>) at ../wlroots-git/backend/libinput/backend.c:58
        event = 0x55b091b0bcc0
        backend = <optimized out>
        ret = <optimized out>
swaywm/sway#7  handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>) at ../wlroots-git/backend/libinput/backend.c:48
        backend = <optimized out>
        ret = <optimized out>
swaywm/sway#8  0x00007fe148d1707a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
swaywm/sway#9  0x00007fe148d14be7 in wl_display_run () at /usr/lib/libwayland-server.so.0
swaywm/sway#10 0x000055b08fd81873 in server_run (server=0x55b08fdf70a0 <server>) at ../sway/sway/server.c:261
        config_path = 0x55b090bdfb60 "/etc/sway/config"
        usage = 0x55b08fdd9240 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options =
            {{name = 0x55b08fdd8332 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55b08fddcb3f "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55b08fdd8337 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55b08fdd8340 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55b08fdd7f07 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55b08fdd791d "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55b08fdd8346 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55b08fdd8355 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55b08fdd8365 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 1
        allow_unsupported_gpu = 0
        verbose = 0
swaywm/sway#11 main (argc=<optimized out>, argv=<optimized out>) at ../sway/sway/main.c:395
        config_path = 0x55b090bdfb60 "/etc/sway/config"
        usage = 0x55b08fdd9240 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = {{name = 0x55b08fdd8332 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55b08fddcb3f "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55b08fdd8337 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55b08fdd8340 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55b08fdd7f07 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55b08fdd791d "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55b08fdd8346 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55b08fdd8355 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55b08fdd8365 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 1
        allow_unsupported_gpu = 0
        verbose = 0
```

- **Description:**
The crash can be reproduced by repeatedly lifting my tablet pen away, and putting it back down on the tablet.

**Comment by Xyene** [comment]
Could you give https://github.com/swaywm/wlroots/pull/3111 a try?
