### ISSUE TITLE
sway: render/wlr_texture.c:29: wlr_texture_from_pixels: Assertion `data' failed.

### ISSUE THREAD

**Issue by minus7** [swaywm/wlroots#3129]
I randomly hit this assertion while browsing with Firefox. Must be rare since I haven't encountered it before and the latest wlroots update was in early July.

Unfortunately, I have neither a core dump nor a backtrace. The logs contain no relevant information at the time of crash other than the assertion in the title.

Sway 1.6.1 with wlroots 0.14.1 on Arch.

**Comment by witi83** [comment]
sway actually dumped for me today (brave instead of firefox) and I also have some backtraces:

```systemd-coredump[108970]: Process 108141 (sway) of user 1000 dumped core.
                                                    
                                                    Found module linux-vdso.so.1 with build-id: 6de083652ed6be47ef40b6562705038dc6894ec5
                                                    Found module libxshmfence.so.1 with build-id: 8876d9ccf620858795724ca24b9e567585a77cec
                                                    Found module libxcb-sync.so.1 with build-id: dda14591103b01b1311906053bf1ca9e82ade35c
                                                    Found module libxcb-dri2.so.0 with build-id: 2dd6e65129a809dab828a1d26215a3f7a363fcc8
                                                    Found module libX11-xcb.so.1 with build-id: 0db4f94d8ae31b8dc9a83f825a9171656f1e532c
                                                    Found module libEGL_mesa.so.0 with build-id: b1e96c7f694a7e4b93f2f0c7b3ce9d5305e6e0aa
                                                    Found module libnss_files.so.2 with build-id: 1a36dfc01d3a1010b2ee79766a24a8090a3266d5
                                                    Found module libicudata.so.69 with build-id: 0ab994a49ef1848499c4af333b3266f28432a922
                                                    Found module libicuuc.so.69 with build-id: 5cf18c56e2f64efdac32cf61fb9c0c48e9bb1797
                                                    Found module libxml2.so.2 with build-id: b9441ffabb52b50c290152592f17cd78a381d493
                                                    Found module libncursesw.so.6 with build-id: 4118a7b0a2a0de8f6359df5b61c6c59a9e13a4d5
                                                    Found module libedit.so.0 with build-id: 4b0babfcad161c2ad0af6e59e2493258db23a331
                                                    Found module libgcc_s.so.1 with build-id: 7f8508bb914546ada778809b64b99d234337d835
                                                    Found module libstdc++.so.6 with build-id: 8ab0e57054dd1dcba681f217016afc6a4e639783
                                                    Found module libvulkan.so.1 with build-id: 7300aecb52d012969b911fe9a6f8774619d4c405
                                                    Found module libdrm_nouveau.so.2 with build-id: 90ddb582b57a61a46d1ebf6c993675f70dac7443
                                                    Found module libdrm_amdgpu.so.1 with build-id: a89ceb7c9082e5276f39023716eb4d194e75f6b8
                                                    Found module libelf.so.1 with build-id: cc912d9cef94d907317afba5edd9176e9828e776
                                                    Found module libdrm_radeon.so.1 with build-id: f6eef9ddb9d1db72080e709ce423f6bad7ea06f7
                                                    Found module libsensors.so.5 with build-id: dc8b2c1c0d8525411aca188ea3cc3fb86d381d30
                                                    Found module libLLVM-12.so with build-id: d1f4954a30a9c39d86e0b944607e0ca8020d651e
                                                    Found module iris_dri.so with build-id: a99437543b242aabeb92155e4434d7fa00d2e25f
                                                    Found module libglapi.so.0 with build-id: 57828fb70af7c1f2aa70b096d748851a1fd39a9c
                                                    Found module libgpg-error.so.0 with build-id: ba85170c2d9343ea05eea8fa2048c212ff4ef552
                                                    Found module libgcrypt.so.20 with build-id: db45f5d5e0f7af1e77324fea1885f974619ad268
                                                    Found module libcap.so.2 with build-id: e56ad9da369b1a7ba6c62d8d31c5a779f07fbbb1
                                                    Found module liblz4.so.1 with build-id: e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                                    Found module libzstd.so.1 with build-id: 4b10444c1560ebc574af4d5f488b7408b22d450e
                                                    Found module liblzma.so.5 with build-id: 8b615460aa230708c5183f16bede67aa0437d95e
                                                    Found module libblkid.so.1 with build-id: f03a24e92c9852272bd0049b5bcb7ed6cf0e664f
                                                    Found module libbrotlicommon.so.1 with build-id: f68934f94312f770550ebc6c5acfd6359b098b07
                                                    Found module libsystemd.so.0 with build-id: f776aaa16b4e2ba7056d01d928e4b2726ffe2b8b
                                                    Found module libgraphite2.so.3 with build-id: 47761dc11e553f519cde97ed9ee985be12ccdae2
                                                    Found module libdatrie.so.1 with build-id: 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                                                    Found module libresolv.so.2 with build-id: c915c72668282861a813f7ea3c0780f37b681dc0
                                                    Found module libmount.so.1 with build-id: ff9a1d99d35cf640d0bfdaba294854372672c29b
                                                    Found module libgmodule-2.0.so.0 with build-id: 34cabbd12d9baf397a0255f174e4c96165bc329b
                                                    Found module libgudev-1.0.so.0 with build-id: a9f734ea9206d637d5aacfbd86298c91cdc1a33a
                                                    Found module libdl.so.2 with build-id: 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                                                    Found module libbrotlidec.so.1 with build-id: f871e6f204ab8d48099915126ba01be989a8000f
                                                    Found module libbz2.so.1.0 with build-id: 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                                                    Found module libexpat.so.1 with build-id: 8850138eae6d9d4d43c5c4b2ac48393bc4279037
                                                    Found module libpangoft2-1.0.so.0 with build-id: 52a846673f7bf9e8acdd0ae9a825926c9cfc5920
                                                    Found module libXdmcp.so.6 with build-id: 8ca0792d23c8b8b4c0864297512349292bea5955
                                                    Found module libXau.so.6 with build-id: 1c67764663e07bec24d8951e5fd93f4d165979ff
                                                    Found module libxcb-errors.so.0 with build-id: 0d6ee255fc30b6a86856b9f1a96491f12a1cacaf
                                                    Found module libxcb-res.so.0 with build-id: b825f66a75478fd00eeb4c57ecb0ac7792e00f5e
                                                    Found module libxcb-icccm.so.4 with build-id: 73f1e12d76af383aa969a60279ed5ed922045f47
                                                    Found module libxcb-composite.so.0 with build-id: 94fff40466ef37eb5973997211aa68f9beb81d15
                                                    Found module libseat.so.1 with build-id: 52de916dc4e54c2b4e14716d051dd46a99b347c7
                                                    Found module libxcb-xinput.so.0 with build-id: 6403174c48f05f40cf7c168beb86f2886b9f09c1
                                                    Found module libxcb-xfixes.so.0 with build-id: a6b197ace5b9b59f913f5969eb419a88d1194f47
                                                    Found module libxcb-render-util.so.0 with build-id: c64fb28ea20a320a9754273d9ea3af85f6f74b17
                                                    Found module libxcb-present.so.0 with build-id: 68f5465258750e2397b1333b3ffc01ee33caa4e1
                                                    Found module libxcb-dri3.so.0 with build-id: 9407a2480e09dc5a1dd9d9a0652fa8d32b328c91
                                                    Found module libEGL.so.1 with build-id: 473944aea0e3dbc5d595dee647702a3cdc0aed78
                                                    Found module libgbm.so.1 with build-id: cd8fa998966b9987180fd6034f3e8b1f02ed50f4
                                                    Found module libdrm.so.2 with build-id: 3aeff5403ca8d7589eabc05752eb613937f454a1
                                                    Found module libwayland-client.so.0 with build-id: 58038363d7ea1fd5e6532f6e5f90b1a3ce09388a
                                                    Found module libGLdispatch.so.0 with build-id: 195b34c1bb271f3b1162c897cfbcfb859e656b93
                                                    Found module libffi.so.7 with build-id: de60e99f39569d11d09160bbdcd486cedc87d2b6
                                                    Found module libharfbuzz.so.0 with build-id: f954dfb80265c0dd2484e766282305a739b8239d
                                                    Found module libthai.so.0 with build-id: 3fdce1a7db2b94d9168eea540dbf5ff5caa3b8ad
                                                    Found module libfribidi.so.0 with build-id: e29e3b231f961d49e628d43ddd1237a8364f788c
                                                    Found module libgio-2.0.so.0 with build-id: 3338d7168eab6039416e1b6dbb7ea3ef213cd129
                                                    Found module librt.so.1 with build-id: 75484da2d6f1515189eefa076e0a40328834cd16
                                                    Found module libwacom.so.2 with build-id: 1d9b89a6d39be5568d5f44888b8a74f46a30c152
                                                    Found module libmtdev.so.1 with build-id: 0cea2a842ae9a0ef02a08477076caab0e5ac5e42
                                                    Found module ld-linux-x86-64.so.2 with build-id: 040cc3dd10461562f177df39e3be2f3704258c3c
                                                    Found module libxcb-shm.so.0 with build-id: fb797f299a446f559a95afcc168227482cc800d1
                                                    Found module libxcb-render.so.0 with build-id: a37bdb37744b508be9dd29fd9ccb9bb0170d43e5
                                                    Found module libXrender.so.1 with build-id: 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                                                    Found module libXext.so.6 with build-id: d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                                                    Found module libX11.so.6 with build-id: e9192497aa39fab51358826d1a1b5fb77edc5081
                                                    Found module libfreetype.so.6 with build-id: 65e7f4a1e5557b0ceeaa433e5356f857fe9c669b
                                                    Found module libfontconfig.so.1 with build-id: 1103a641395c7d3b42e49b793d3a9ea927c77bf6
                                                    Found module libpng16.so.16 with build-id: 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                                                    Found module libz.so.1 with build-id: 81bf6e728a6d6f5b105b0f8b25f6c614ce10452a
                                                    Found module libpthread.so.0 with build-id: 07c8f95b4f3251d08550217ad8a1f31066229996
                                                    Found module libc.so.6 with build-id: 4b406737057708c0e4c642345a703c47a61c73dc
                                                    Found module libpangocairo-1.0.so.0 with build-id: 2554be0474a6ee311b6e9aa4fd79a244167cdcfd
                                                    Found module libxcb.so.1 with build-id: 0d1ef11740a5daad2ee331e812a51aa6574af222
                                                    Found module libxkbcommon.so.0 with build-id: 1f1bc7527e57c886c3df5803068122e1971d4724
                                                    Found module libwlroots.so.9 with build-id: b0a3eaf1e7b40cf9b49677901af2dc7f22b718b2
                                                    Found module libwayland-server.so.0 with build-id: 232648aebf61c9b61940ac383dbe27984deea6b2
                                                    Found module libpixman-1.so.0 with build-id: 341f793dcada3a48a306a793d265a517e3f2e7d6
                                                    Found module libGLESv2.so.2 with build-id: a56281a2afd5eea8cd258ea2487094cd322e8c7e
                                                    Found module libpcre.so.1 with build-id: 845483dd0acba86de9f0313102bebbaf3ce52767
                                                    Found module libglib-2.0.so.0 with build-id: 1fe1592d097fa28822c23e96d9f357583b48424d
                                                    Found module libgobject-2.0.so.0 with build-id: 0eaa1a0f88089b3dcf33eedf51105a54beeeea9a
                                                    Found module libpango-1.0.so.0 with build-id: 5deae7c16592ea404754114e8ae56ddf9cf4ca7e
                                                    Found module libm.so.6 with build-id: 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                                                    Found module libudev.so.1 with build-id: 880e57f50a36ddbfe80dbe5f62d43860f960c797
                                                    Found module libinput.so.10 with build-id: 98dd687bf58a7ce56301f1738d6594d2c24162cb
                                                    Found module libevdev.so.2 with build-id: 8e76bb802fb22b11afd8e730e0a74cc8e25c03f5
                                                    Found module libjson-c.so.5 with build-id: abd35760ae61d5674132015f99bf33851be07ec2
                                                    Found module libcairo.so.2 with build-id: 06820af9cf79c2deb207d9533a61caf04e67a8ad
                                                    Found module sway with build-id: 4d12ebcc39e4a707b1a9f0b3c18b7218b26ee413
                                                    Stack trace of thread 108141:
                                                    #0  0x00007ff9d3783d22 raise (libc.so.6 + 0x3cd22)
                                                    #1  0x00007ff9d376d862 abort (libc.so.6 + 0x26862)
                                                    #2  0x00007ff9d376d747 __assert_fail_base.cold (libc.so.6 + 0x26747)
                                                    #3  0x00007ff9d377c616 __assert_fail (libc.so.6 + 0x35616)
                                                    #4  0x00007ff9d39be443 wlr_texture_from_pixels (libwlroots.so.9 + 0x27443)
                                                    #5  0x000055b2e4d39885 n/a (sway + 0x52885)
                                                    #6  0x000055b2e4d3cd0e n/a (sway + 0x55d0e)
                                                    #7  0x000055b2e4d48c8f n/a (sway + 0x61c8f)
                                                    #8  0x000055b2e4d05a62 n/a (sway + 0x1ea62)
                                                    #9  0x00007ff9d3a0a1ee wlr_signal_emit_safe (libwlroots.so.9 + 0x731ee)
                                                    #10 0x00007ff9d3155acd n/a (libffi.so.7 + 0x6acd)
                                                    #11 0x00007ff9d315503a n/a (libffi.so.7 + 0x603a)
                                                    #12 0x00007ff9d3a5d124 n/a (libwayland-server.so.0 + 0xd124)
                                                    #13 0x00007ff9d3a5857c n/a (libwayland-server.so.0 + 0x857c)
                                                    #14 0x00007ff9d3a5b07a wl_event_loop_dispatch (libwayland-server.so.0 + 0xb07a)
                                                    #15 0x00007ff9d3a58be7 wl_display_run (libwayland-server.so.0 + 0x8be7)
                                                    #16 0x000055b2e4cf797b n/a (sway + 0x1097b)
                                                    #17 0x00007ff9d376eb25 __libc_start_main (libc.so.6 + 0x27b25)
                                                    #18 0x000055b2e4cf7cee n/a (sway + 0x10cee)
                                                    
                                                    Stack trace of thread 108151:
                                                    #0  0x00007ff9d37398ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                    #1  0x00007ff9d3733270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                    #2  0x00007ff9d111488c n/a (iris_dri.so + 0x1c888c)
                                                    #3  0x00007ff9d110df68 n/a (iris_dri.so + 0x1c1f68)
                                                    #4  0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #5  0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
                                                    
                                                    Stack trace of thread 108154:
                                                    #0  0x00007ff9d37398ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                    #1  0x00007ff9d3733270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                    #2  0x00007ff9d111488c n/a (iris_dri.so + 0x1c888c)
                                                    #3  0x00007ff9d110df68 n/a (iris_dri.so + 0x1c1f68)
                                                    #4  0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #5  0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
                                                    
                                                    Stack trace of thread 108152:
                                                    #0  0x00007ff9d37398ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                    #1  0x00007ff9d3733270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                    #2  0x00007ff9d111488c n/a (iris_dri.so + 0x1c888c)
                                                    #3  0x00007ff9d110df68 n/a (iris_dri.so + 0x1c1f68)
                                                    #4  0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #5  0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
                                                    
                                                    Stack trace of thread 108153:
                                                    #0  0x00007ff9d37398ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                    #1  0x00007ff9d3733270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                    #2  0x00007ff9d111488c n/a (iris_dri.so + 0x1c888c)
                                                    #3  0x00007ff9d110df68 n/a (iris_dri.so + 0x1c1f68)
                                                    #4  0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #5  0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
                                                    
                                                    Stack trace of thread 108155:
                                                    #0  0x00007ff9d37398ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                    #1  0x00007ff9d3733270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                    #2  0x00007ff9d111488c n/a (iris_dri.so + 0x1c888c)
                                                    #3  0x00007ff9d110df68 n/a (iris_dri.so + 0x1c1f68)
                                                    #4  0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #5  0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
                                                    
                                                    Stack trace of thread 108968:
                                                    #0  0x00007ff9d36a332c n/a (libfontconfig.so.1 + 0x1f32c)
                                                    #1  0x00007ff9d3785535 msort_with_tmp.part.0 (libc.so.6 + 0x3e535)
                                                    #2  0x00007ff9d37854c2 msort_with_tmp.part.0 (libc.so.6 + 0x3e4c2)
                                                    #3  0x00007ff9d37854a5 msort_with_tmp.part.0 (libc.so.6 + 0x3e4a5)
                                                    #4  0x00007ff9d37854c2 msort_with_tmp.part.0 (libc.so.6 + 0x3e4c2)
                                                    #5  0x00007ff9d37854a5 msort_with_tmp.part.0 (libc.so.6 + 0x3e4a5)
                                                    #6  0x00007ff9d37854c2 msort_with_tmp.part.0 (libc.so.6 + 0x3e4c2)
                                                    #7  0x00007ff9d378588a qsort_r (libc.so.6 + 0x3e88a)
                                                    #8  0x00007ff9d36aad19 FcFontSetSort (libfontconfig.so.1 + 0x26d19)
                                                    #9  0x00007ff9d2fc031e n/a (libpangoft2-1.0.so.0 + 0x831e)
                                                    #10 0x00007ff9d3c1dd11 n/a (libglib-2.0.so.0 + 0x82d11)
                                                    #11 0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #12 0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
                                                    
                                                    Stack trace of thread 108158:
                                                    #0  0x00007ff9d37398ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
                                                    #1  0x00007ff9d3733270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
                                                    #2  0x00007ff9d111488c n/a (iris_dri.so + 0x1c888c)
                                                    #3  0x00007ff9d110df68 n/a (iris_dri.so + 0x1c1f68)
                                                    #4  0x00007ff9d372d259 start_thread (libpthread.so.0 + 0x9259)
                                                    #5  0x00007ff9d38455e3 __clone (libc.so.6 + 0xfe5e3)
```

Setup is the same: Sway 1.6.1 with wlroots 0.14.1 on Arch.

**Comment by tirsek** [comment]
I encountered this crash today and can reliably reproduce it by going to https://www.uscis.gov/ in Chromium, then signing in. The sign-in page loads fine, but after sign-in and 2FA verification, Sway crashes with this assertion and dumps core. I'll see if I can find some time to build the relevant things with symbols to get more details, but at least I have a way to reproduce it.

Arch Linux, chromium 94.0.4606.61-1, wlroots 0.14.1-2, sway 1:1.6.1-1

**Comment by minus7** [comment]
In wlroots, only [wlr_output_cursor_set_image](https://github.com/swaywm/wlroots/blob/49a574420138646845fb664862db03982cfd9f5b/types/wlr_output.c#L1391) calls it with a null check the line before.
Sway only calls it from [render_titlebar_text_texture](https://github.com/swaywm/sway/blob/3b1effdfa5f4777799f4fc3da00554b5b8d035e0/sway/tree/container.c#L560) with a directly created image via cairo doing no error checks. So either this fails because the e.g. the titlebar text width goes egregiously wide (there does not seem to be a cap) and it fails to allocate, or something somewhere much worse happens.

**Comment by tirsek** [comment]
@minus7, it looks like your guess is spot on. My crash happens during a titlebar text update with a frankly unreasonably long text:

```
#4  0x00007f35b18a8557 in wlr_texture_from_pixels
    (renderer=<optimized out>, fmt=<optimized out>, stride=<optimized out>, width=<optimized out>, height=<optimized out>, data=<optimized out>) at ../wlroots-0.14.1/render/wlr_texture.c:29
#5  0x000056372270cfd5 in update_title_texture
    (con=con@entry=0x56372450b520, texture=texture@entry=0x56372450b6e8, class=<optimized out>)
    at ../sway-1.6.1/sway/tree/container.c:560
#6  0x00005637227104d2 in container_update_title_textures (container=0x56372450b520)
    at ../sway-1.6.1/sway/tree/container.c:568
#7  0x000056372271c6d3 in view_update_title (view=0x5637241a79a0, force=<optimized out>)
    at ../sway-1.6.1/sway/tree/view.c:1291
#8  0x000056372271d81a in handle_set_title (listener=0x5637241a7ba8, data=<optimized out>)
    at ../sway-1.6.1/sway/desktop/xwayland.c:621
#9  0x00007f35b18f5abe in wlr_signal_emit_safe (signal=signal@entry=0x5637241a78c8, data=data@entry=0x5637241a7720)
    at ../wlroots-0.14.1/util/signal.c:29
#10 0x00007f35b18f77c5 in read_surface_title
    (xwm=<optimized out>, xwm=<optimized out>, reply=0x5637245d85c0, xsurface=0x5637241a7720)
    at ../wlroots-0.14.1/xwayland/xwm.c:496
#11 read_surface_property (xwm=<optimized out>, xsurface=0x5637241a7720, property=<optimized out>)
    at ../wlroots-0.14.1/xwayland/xwm.c:775
#12 0x00007f35b18fc3a1 in xwm_handle_property_notify (ev=0x5637241a9f10, xwm=0x5637241aaba0)
    at ../wlroots-0.14.1/xwayland/xwm.c:1083
#13 x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wlroots-0.14.1/xwayland/xwm.c:1529
#14 x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wlroots-0.14.1/xwayland/xwm.c:1481
#15 0x00007f35b194707a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#16 0x00007f35b1944be7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#17 0x00005637226ca980 in server_run (server=0x56372273f0a0 <server>) at ../sway-1.6.1/sway/server.c:254
#18 main (argc=<optimized out>, argv=0x7ffd781c7c88) at ../sway-1.6.1/sway/main.c:433

(gdb) frame 5
#5  0x000056372270cfd5 in update_title_texture (con=con@entry=0x56372450b520, texture=texture@entry=0x56372450b6e8, 
    class=<optimized out>) at ../sway-1.6.1/sway/tree/container.c:560
560             *texture = wlr_texture_from_pixels(

(gdb) l 529,561
529		get_text_size(c, config->font, &width, NULL, NULL, scale,
530				config->pango_markup, "%s", con->formatted_title);
531		cairo_surface_destroy(dummy_surface);
532		cairo_destroy(c);
533	
534		if (width == 0 || height == 0) {
535			return;
536		}
537	
538		cairo_surface_t *surface = cairo_image_surface_create(
539				CAIRO_FORMAT_ARGB32, width, height);
540		cairo_t *cairo = cairo_create(surface);
541		cairo_set_antialias(cairo, CAIRO_ANTIALIAS_BEST);
542		cairo_set_font_options(cairo, fo);
543		cairo_font_options_destroy(fo);
544		cairo_set_source_rgba(cairo, class->background[0], class->background[1],
545				class->background[2], class->background[3]);
546		cairo_paint(cairo);
547		PangoContext *pango = pango_cairo_create_context(cairo);
548		cairo_set_source_rgba(cairo, class->text[0], class->text[1],
549				class->text[2], class->text[3]);
550		cairo_move_to(cairo, 0, 0);
551	
552		pango_printf(cairo, config->font, scale, config->pango_markup,
553				"%s", con->formatted_title);
554	
555		cairo_surface_flush(surface);
556		unsigned char *data = cairo_image_surface_get_data(surface);
557		int stride = cairo_format_stride_for_width(CAIRO_FORMAT_ARGB32, width);
558		struct wlr_renderer *renderer = wlr_backend_get_renderer(
559				output->wlr_output->backend);
560		*texture = wlr_texture_from_pixels(
561				renderer, DRM_FORMAT_ARGB8888, stride, width, height, data);

(gdb) p config->font
$25 = 0x563723d1b1e0 "Dejavu Sans Condensed 10"
(gdb) p $_strlen(con->formatted_title)
$26 = 3655
(gdb) p width
$27 = 54704
(gdb) p height
$28 = 34
(gdb) p stride
$29 = 218816
```

The `surface`, `cairo`, and `pango` pointers are all non-null, although gdb doesn't have detailed type information about them to inspect their contents.

**Comment by tirsek** [comment]
I'm not at all familiar with the code, but perhaps the title width could simply be clamped to the width of the output; something like this:

```diff
diff --git a/sway/tree/container.c b/sway/tree/container.c
index 2b51a723..07059492 100644
--- a/sway/tree/container.c
+++ b/sway/tree/container.c
@@ -535,6 +535,10 @@ static void update_title_texture(struct sway_container *con,
                return;
        }
 
+       if (width > output->width * scale) {
+               width = output->width * scale;
+       }
+
        cairo_surface_t *surface = cairo_image_surface_create(
                        CAIRO_FORMAT_ARGB32, width, height);
        cairo_t *cairo = cairo_create(surface);
```

I assume multiplying by the scale is necessary here, otherwise the title appears to be cut short. I would imagine that this could cause problems if a container is moved from one output to another having a higher resolution, but I did a quick test with two such outputs here, and couldn't immediately get the title to truncate, so perhaps this is adequate.

**Comment by RPigott** [comment]
Is this a dupe of swaywm/sway#6531?

**Comment by minus7** [comment]
Yes indeed, closing this one since it's not a wlroots issue anyway.

**Comment by emersion** [comment]
I think it'd be worthwhile to add a NULL check too, in addition to adding a width limit.
