### ISSUE TITLE
rootston: Assertion fails when releasing mouse button after selection

### ISSUE THREAD

**Issue by chebykinn** [swaywm/wlroots#649]
__Commit:__ 868ad5af69583646ba71d6e73e362818c7416941
__Reproduction:__ Select text in window and release mouse in GTK application (e. g. gnome-terminal)
__Result:__
```
../types/wlr_seat.c:1313: wlr_seat_client_from_resource: Assertion `wl_resource_instance_of(resource, &wl_seat_interface, &wl_seat_impl)' failed.
```
If I remove this assertion, selection works fine.

**Comment by Ongy** [comment]
Can you please attach a stacktrace? (coredumpctl is your friend)
I can't reproduce this with `gnome-terminal`, which is gtk-3 for me. Which application did you encounter this with?

**Comment by chebykinn** [comment]
Hmm, I'm using Arch, gtk3 version 3.22.28

**Comment by martinetd** [comment]
I could reproduce by running gnome-terminal + urxvt. click mouse button down on gnome-terminal, alt-tab to urxvt, release button on urxvt.

Stacktrace:
```
rootston: ../types/wlr_seat.c:1313: wlr_seat_client_from_resource: Assertion `wl_resource_instance_of(resource, &wl_seat_interface, &wl_seat_impl)' failed.
#1  0x00007ffff5b06ec9 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5afe0bc in __assert_fail_base () at /usr/lib/libc.so.6
#3  0x00007ffff5afe133 in  () at /usr/lib/libc.so.6
#4  0x00007ffff6bad203 in wlr_seat_client_from_resource (resource=0x60c0000af0c0) at ../types/wlr_seat.c:1312
#5  0x00007ffff6ba4ce9 in device_handle_set_selection (client=0x61000028e540, resource=0x60c0000af0c0, source_resource=0x60c0000b1340, serial=53)
    at ../types/wlr_primary_selection.c:267
#6  0x00007ffff2a831c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#7  0x00007ffff2a82c2a in ffi_call () at /usr/lib/libffi.so.6
#8  0x00007ffff68fd7fd in  () at /usr/lib/libwayland-server.so.0
#9  0x00007ffff68f9f79 in  () at /usr/lib/libwayland-server.so.0
#10 0x00007ffff68fb9b2 in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#11 0x00007ffff68fa14c in wl_display_run ()
    at /usr/lib/libwayland-server.so.0
#12 0x0000555555571a6a in main (argc=1, argv=0x7fffffffe3f8)
    at ../rootston/main.c:81
```
