### ISSUE TITLE
rootston crash on focus change with xwayland popup

### ISSUE THREAD

**Issue by Ongy** [swaywm/wlroots#671]
Reproduce (may be overly specific):
* Open firefox and termite in rootston
* ~~Place firefox and termite in a way, such that right click menu of firefox is over termite~~ Not required
* Right click on firefox
* Hover the menu and [Alt]+[Tab] to change focus to termite
* [Alt]+[Tab] back to firefox

```
           PID: 4591 (rootston)
           UID: 1000 (ongy)
           GID: 1000 (ongy)
        Signal: 11 (SEGV)
     Timestamp: Sun 2018-02-25 10:08:21 CET (30s ago)
  Command Line: /home/ongy/Source/wlroots/build/rootston/rootston -E termite
    Executable: /home/ongy/Source/wlroots/build/rootston/rootston
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (ongy)
       Boot ID: 0146d6ac264047c6ad34c6f2a2211f28
    Machine ID: e47085c8d34048d7b5485047dcf6fdeb
      Hostname: link
       Storage: /var/lib/systemd/coredump/core.rootston.1000.0146d6ac264047c6ad34c6f2a2211f28.4591.1519549701000000.lz4
       Message: Process 4591 (rootston) of user 1000 dumped core.
                
                Stack trace of thread 4591:
                #0  0x00007f5f60343137 wl_list_remove (libwayland-server.so.0)
                #1  0x00005570d8e1e4fa n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #2  0x00005570d8e1e76d n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #3  0x00005570d8e1898a n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #4  0x00005570d8e18dbc n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #5  0x00005570d8e18f96 n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #6  0x00005570d8e1c5db n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #7  0x00007f5f6059eb27 n/a (/home/ongy/Source/wlroots/build/libwlroots.so.0.0.0)
                #8  0x00007f5f60587309 n/a (/home/ongy/Source/wlroots/build/libwlroots.so.0.0.0)
                #9  0x00007f5f60578048 n/a (/home/ongy/Source/wlroots/build/libwlroots.so.0.0.0)
                #10 0x00007f5f5d0891c8 ffi_call_unix64 (libffi.so.6)
                #11 0x00007f5f5d088c2a ffi_call (libffi.so.6)
                #12 0x00007f5f5ee84bad n/a (libwayland-client.so.0)
                #13 0x00007f5f5ee81679 n/a (libwayland-client.so.0)
                #14 0x00007f5f5ee829b4 wl_display_dispatch_queue_pending (libwayland-client.so.0)
                #15 0x00007f5f605757e0 n/a (/home/ongy/Source/wlroots/build/libwlroots.so.0.0.0)
                #16 0x00007f5f603409b2 wl_event_loop_dispatch (libwayland-server.so.0)
                #17 0x00007f5f6033f14c wl_display_run (libwayland-server.so.0)
                #18 0x00005570d8e19a50 n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
                #19 0x00007f5f5f535f4a __libc_start_main (libc.so.6)
                #20 0x00005570d8e1209a n/a (/home/ongy/Source/wlroots/build/rootston/rootston)
```

Without any further investigation, I think it is caused by the same problem as https://github.com/swaywm/wlroots/issues/650

**Comment by emersion** [comment]
Can you dump the coredump and run `gdb rootston coredump` to get the full stack trace?

**Comment by Ongy** [comment]
```
#0  0x00007ffff795c137 in wl_list_remove () at /usr/lib/libwayland-server.so.0
#1  0x00005555555654fa in roots_seat_set_focus (seat=0x555555788c10, view=0x555555af49f0) at ../rootston/seat.c:713
#2  0x000055555556576d in roots_seat_cycle_focus (seat=0x555555788c10) at ../rootston/seat.c:785
#3  0x000055555555f98a in keyboard_binding_execute (keyboard=0x5555559459e0, command=0x55555577f450 "next_window") at ../rootston/keyboard.c:108
#4  0x000055555555fdbc in keyboard_execute_binding (keyboard=0x5555559459e0, pressed_keysyms=0x555555945a58, modifiers=8, keysyms=0x55555591a778, keysyms_len=1)
    at ../rootston/keyboard.c:203
#5  0x000055555555ff96 in roots_keyboard_handle_key (keyboard=0x5555559459e0, event=0x7fffffffd940) at ../rootston/keyboard.c:268
#6  0x00005555555635db in handle_keyboard_key (listener=0x555555945a28, data=0x7fffffffd940) at ../rootston/seat.c:21
#7  0x00007ffff7bb7b27 in wlr_signal_emit_safe (signal=0x555555945918, data=0x7fffffffd940) at ../util/signal.c:29
#8  0x00007ffff7ba0309 in wlr_keyboard_notify_key (keyboard=0x555555945820, event=0x7fffffffd940) at ../types/wlr_keyboard.c:136
#9  0x00007ffff7b91048 in keyboard_handle_key (data=0x555555945790, wl_keyboard=0x555555945970, serial=17111, time=6887321, key=15, state=1) at ../backend/wayland/wl_seat.c:172
#10 0x00007ffff46a21c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#11 0x00007ffff46a1c2a in ffi_call () at /usr/lib/libffi.so.6
#12 0x00007ffff649dbad in  () at /usr/lib/libwayland-client.so.0
#13 0x00007ffff649a679 in  () at /usr/lib/libwayland-client.so.0
#14 0x00007ffff649b9b4 in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#15 0x00007ffff7b8e7e0 in dispatch_events (fd=4, mask=1, data=0x55555577f5a0) at ../backend/wayland/backend.c:28
#16 0x00007ffff79599b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#17 0x00007ffff795814c in wl_display_run () at /usr/lib/libwayland-server.so.0
#18 0x0000555555560a50 in main (argc=3, argv=0x7fffffffe018) at ../rootston/main.c:81
```
