### ISSUE TITLE
Cannot start rootston inside rooston inside X11

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#766]
```
(gdb) bt
#0  0x00007ffff6bb7e36 in __strlen_sse2 () at /usr/lib/libc.so.6
#1  0x00007ffff6ba7b8e in strdup () at /usr/lib/libc.so.6
#2  0x00007ffff17b32cc in  () at /usr/lib/libEGL_mesa.so.0
#3  0x00007ffff17a6913 in  () at /usr/lib/libEGL_mesa.so.0
#4  0x00007ffff179ced0 in  () at /usr/lib/libEGL_mesa.so.0
#5  0x00007ffff7b8de31 in wlr_egl_bind_display (egl=0x555555783cf8, 
local_display=0x55555577d700) at ../render/egl.c:215
#6  0x00007ffff7b866a0 in wlr_wl_backend_create (display=0x55555577d700, 
remote=0x0)
    at ../backend/wayland/backend.c:213
#7  0x00007ffff7b787d6 in attempt_wl_backend (display=0x55555577d700)
    at ../backend/backend.c:65
#8  0x00007ffff7b784cd in wlr_backend_autocreate (display=0x55555577d700)
    at ../backend/backend.c:95
#9  0x0000555555562a91 in main (argc=1, argv=0x7fffffffe5d8) at 
../rootston/main.c:35
```

**Comment by SirCmpwn** [comment]
Cannot start rootston in rootston in rootston in rootston in rootston in

**Comment by emersion** [comment]
rootston is not in the wlroots tree anymore.
