### ISSUE TITLE
Random xwm crash

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#898]
One element in the list is corrupted.

```
#0  0x00007fe6d7a638ee in lookup_surface (xwm=0x55acc734d120, window_id=4194305)
    at ../subprojects/wlroots/xwayland/xwm.c:98
#1  0x00007fe6d7a62ca0 in xwm_handle_configure_notify (xwm=0x55acc734d120, ev=0x55acc72ec2b0) at ../subprojects/wlroots/xwayland/xwm.c:751
#2  0x00007fe6d7a61a29 in x11_event_handler (fd=15, mask=1, data=0x55acc734d120)
    at ../subprojects/wlroots/xwayland/xwm.c:1162
#3  0x00007fe6d5fa39b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#4  0x00007fe6d5fa214c in wl_display_run () at /usr/lib/libwayland-server.so.0
#5  0x000055acc59fd354 in server_run (server=0x55acc5c382a0 <server>)
    at ../sway/server.c:141
#6  0x000055acc59fc532 in main (argc=1, argv=0x7fff64205578) at ../sway/main.c:418
(gdb) print xwm
$1 = (struct wlr_xwm *) 0x55acc734d120
(gdb) print surface
$2 = (struct wlr_xwayland_surface *) 0xffffffffffffffe8
(gdb) print xwm->surfaces.next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next
$38 = (struct wl_list *) 0x0
```

**Comment by emersion** [comment]
Not seen this in a while, probably one of these memory corruption issues.
